/**
 * generated by Xtext
 */
package fr.tpt.aadl.ramses.transformation.trc.xtext.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class TRCDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
