/**
 * generated by Xtext
 */
package org.trc.xtext.dsl.validation;

import org.trc.xtext.dsl.validation.AbstractDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DslValidator extends AbstractDslValidator {
}
