#include "arinc653/sampling.h"
#include "arinc653/blackboard.h"
#include "business-code/PingPong_module.h"
#include "subprograms.h"
PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_State_t S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_init_state;
void PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl(SEQ *  seqNb, BLACKBOARD_ID_TYPE *  delayed_PongIn, SAMPLING_PORT_ID_TYPE *  mode_aadlKeywords, SAMPLING_PORT_ID_TYPE *  PortCnx6_PingOut, SAMPLING_PORT_ID_TYPE *  PortCnx8_badSequenceNumber, PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_currentState *  Parent_BA_currentState_Access, Base_Types__Integer_16 *  PingOut_freshnessIndicator_access)
{
  PingPongMessage PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_Length = sizeof(PingPongMessage);
  PingPong_refined_model__PingPongMessage_freshness_t_impl PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_PingOut_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_PingOut_Length = sizeof(PingPong_refined_model__PingPongMessage_freshness_t_impl);
  Exception PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_badSequenceNumber_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_badSequenceNumber_Length = sizeof(Exception);
  ROLE PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_Length = sizeof(ROLE);
  RETURN_CODE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_ErrorCode = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_ErrorCode = 0;
  VALIDITY_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_Validity;
  SYSTEM_TIME_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_TimeOut = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_S2_inst_IPingOrPong_Cping_ping_runtime_call_ret;
  PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_behaviorIdentifier_enum whichPortActivated = PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_current_state)
  {
    case PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_S2_inst_IPingOrPong_Cping_ping_runtime_call_ret);
      break;
    }
    case PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_behaviorIdentifier_enum_default_behavior)
    {
      S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_currentState_switch) {
      READ_BLACKBOARD ((*delayed_PongIn), PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_TimeOut, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_localVariable, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_Length, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_S2_inst_IPingOrPong_Cping_ping_runtime_call_ret);
      READ_SAMPLING_MESSAGE ((*mode_aadlKeywords), &PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_localVariable, PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_Length, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_Validity, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_S2_inst_IPingOrPong_Cping_ping_runtime_call_ret);
      if (PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_localVariable == E_ROLE_CPING) {
      IPingOrPong_Cping_ping (&PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_localVariable, &(PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_PingOut_localVariable.pvalue), &PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_badSequenceNumber_localVariable, seqNb, seqNb);
      }
      (*PingOut_freshnessIndicator_access) = (*PingOut_freshnessIndicator_access) + 1;
      PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_PingOut_localVariable.fresh_ba = (*PingOut_freshnessIndicator_access);
      WRITE_SAMPLING_MESSAGE ((*PortCnx6_PingOut), &PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_PingOut_localVariable, PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_PingOut_Length, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_S2_inst_IPingOrPong_Cping_ping_runtime_call_ret);
      WRITE_SAMPLING_MESSAGE ((*PortCnx8_badSequenceNumber), &PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_badSequenceNumber_localVariable, PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_badSequenceNumber_Length, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_S2_inst_IPingOrPong_Cping_ping_runtime_call_ret);
      PERIODIC_WAIT (&PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_entrypoint_impl_S2_inst_IPingOrPong_Cping_ping_runtime_call_ret);
      (*Parent_BA_currentState_Access) = PingPong_refined_model__S2_inst_IPingOrPong_Cping_ping_currentState_switch;
      }
      break;
    }
  }
}
}
void PingPong__IPingOrPong_Cping_delayed_PongIn(PingPongMessage *  PongIn, PingPongMessage *  delayed_PongIn)
{
}
PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_State_t S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_init_state;
void PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl(SEQ *  seqNb, SAMPLING_PORT_ID_TYPE *  PongIn, SAMPLING_PORT_ID_TYPE *  mode_aadlKeywords, BLACKBOARD_ID_TYPE *  PortCnx9_delayed_PongIn, PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_currentState *  Parent_BA_currentState_Access)
{
  PingPongMessage PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_Length = sizeof(PingPongMessage);
  PingPongMessage PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_delayed_PongIn_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_delayed_PongIn_Length = sizeof(PingPongMessage);
  ROLE PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_Length = sizeof(ROLE);
  RETURN_CODE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_ErrorCode = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_ErrorCode = 0;
  VALIDITY_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_Validity;
  VALIDITY_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_Validity;
  RETURN_CODE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S2_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret;
  PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_behaviorIdentifier_enum whichPortActivated = PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_current_state)
  {
    case PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S2_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret);
      break;
    }
    case PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_behaviorIdentifier_enum_default_behavior)
    {
      S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_currentState_switch) {
      READ_SAMPLING_MESSAGE ((*PongIn), &PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_localVariable, PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_Length, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_Validity, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S2_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret);
      READ_SAMPLING_MESSAGE ((*mode_aadlKeywords), &PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_localVariable, PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_Length, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_Validity, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S2_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret);
      if (PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_localVariable == E_ROLE_CPING) {
      PingPong__IPingOrPong_Cping_delayed_PongIn (&PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_localVariable, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_delayed_PongIn_localVariable);
      }
      DISPLAY_BLACKBOARD ((*PortCnx9_delayed_PongIn), &PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_delayed_PongIn_localVariable, PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_delayed_PongIn_Length, &PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S2_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret);
      PERIODIC_WAIT (&PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S2_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret);
      (*Parent_BA_currentState_Access) = PingPong_refined_model__S2_inst_IPingOrPong_Cping_delayed_PongIn_currentState_switch;
      }
      break;
    }
  }
}
}
PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_State_t S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_init_state;
void PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl(SEQ *  seqNb, SAMPLING_PORT_ID_TYPE *  PingIn, SAMPLING_PORT_ID_TYPE *  mode_aadlKeywords, SAMPLING_PORT_ID_TYPE *  PortCnx7_PongOut, PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_currentState *  Parent_BA_currentState_Access, Base_Types__Integer_16 *  PingIn_freshnessIndicator_access)
{
  PingPong_refined_model__PingPongMessage_freshness_t_impl PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_Length = sizeof(PingPong_refined_model__PingPongMessage_freshness_t_impl);
  PingPongMessage PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PongOut_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PongOut_Length = sizeof(PingPongMessage);
  ROLE PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_Length = sizeof(ROLE);
  RETURN_CODE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_ErrorCode = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_ErrorCode = 0;
  VALIDITY_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_Validity;
  VALIDITY_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_Validity;
  RETURN_CODE_TYPE PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_S2_inst_IPingOrPong_Cpong_pong_runtime_call_ret;
  PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_behaviorIdentifier_enum whichPortActivated = PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_current_state)
  {
    case PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_S2_inst_IPingOrPong_Cpong_pong_runtime_call_ret);
      break;
    }
    case PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_behaviorIdentifier_enum_default_behavior)
    {
      S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_current_state = PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_currentState_switch) {
      READ_SAMPLING_MESSAGE ((*PingIn), &PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_localVariable, PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_Length, &PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_Validity, &PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_S2_inst_IPingOrPong_Cpong_pong_runtime_call_ret);
      READ_SAMPLING_MESSAGE ((*mode_aadlKeywords), &PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_localVariable, PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_Length, &PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_Validity, &PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_S2_inst_IPingOrPong_Cpong_pong_runtime_call_ret);
      if (PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_localVariable == E_ROLE_CPONG) {
      if ((PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_localVariable.fresh_ba != (*PingIn_freshnessIndicator_access))) {
      IPingOrPong_Cpong_pong (&PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_localVariable.pvalue, &PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PongOut_localVariable);
      }
      }
      (*PingIn_freshnessIndicator_access) = PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_localVariable.fresh_ba;
      WRITE_SAMPLING_MESSAGE ((*PortCnx7_PongOut), &PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PongOut_localVariable, PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PongOut_Length, &PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_S2_inst_IPingOrPong_Cpong_pong_runtime_call_ret);
      PERIODIC_WAIT (&PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_entrypoint_impl_S2_inst_IPingOrPong_Cpong_pong_runtime_call_ret);
      (*Parent_BA_currentState_Access) = PingPong_refined_model__S2_inst_IPingOrPong_Cpong_pong_currentState_switch;
      }
      break;
    }
  }
}
}
