/*
* generated by Xtext
*/
package fr.tpt.aadl.ramses.transformation.trc.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import fr.tpt.aadl.ramses.transformation.trc.xtext.services.TRCGrammarAccess;

public class TRCParser extends AbstractContentAssistParser {
	
	@Inject
	private TRCGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected fr.tpt.aadl.ramses.transformation.trc.xtext.ui.contentassist.antlr.internal.InternalTRCParser createParser() {
		fr.tpt.aadl.ramses.transformation.trc.xtext.ui.contentassist.antlr.internal.InternalTRCParser result = new fr.tpt.aadl.ramses.transformation.trc.xtext.ui.contentassist.antlr.internal.InternalTRCParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getRuleDependencyCompositeAccess().getAlternatives(), "rule__RuleDependencyComposite__Alternatives");
					put(grammarAccess.getAbstractRuleDependencyAccess().getAlternatives(), "rule__AbstractRuleDependency__Alternatives");
					put(grammarAccess.getRuleDependencyAccess().getTypeAlternatives_0_0(), "rule__RuleDependency__TypeAlternatives_0_0");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getEssentialOCLUnreservedNameAccess().getAlternatives(), "rule__EssentialOCLUnreservedName__Alternatives");
					put(grammarAccess.getPrimitiveTypeIdentifierAccess().getAlternatives(), "rule__PrimitiveTypeIdentifier__Alternatives");
					put(grammarAccess.getCollectionTypeIdentifierAccess().getAlternatives(), "rule__CollectionTypeIdentifier__Alternatives");
					put(grammarAccess.getTrcSpecificationAccess().getGroup(), "rule__TrcSpecification__Group__0");
					put(grammarAccess.getModuleListAccess().getGroup(), "rule__ModuleList__Group__0");
					put(grammarAccess.getModuleListAccess().getGroup_4(), "rule__ModuleList__Group_4__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getModuleAccess().getGroup(), "rule__Module__Group__0");
					put(grammarAccess.getModuleAccess().getGroup_4(), "rule__Module__Group_4__0");
					put(grammarAccess.getModuleAccess().getGroup_4_2(), "rule__Module__Group_4_2__0");
					put(grammarAccess.getTransformationListAccess().getGroup(), "rule__TransformationList__Group__0");
					put(grammarAccess.getTransformationListAccess().getGroup_3(), "rule__TransformationList__Group_3__0");
					put(grammarAccess.getTransformationAccess().getGroup(), "rule__Transformation__Group__0");
					put(grammarAccess.getTransformationAccess().getGroup_5(), "rule__Transformation__Group_5__0");
					put(grammarAccess.getTransformationAccess().getGroup_6(), "rule__Transformation__Group_6__0");
					put(grammarAccess.getTransformationAccess().getGroup_6_3(), "rule__Transformation__Group_6_3__0");
					put(grammarAccess.getTransformationImpactAccess().getGroup(), "rule__TransformationImpact__Group__0");
					put(grammarAccess.getTransformationImpactAccess().getGroup_1(), "rule__TransformationImpact__Group_1__0");
					put(grammarAccess.getTransformationDependencyListAccess().getGroup(), "rule__TransformationDependencyList__Group__0");
					put(grammarAccess.getTransformationDependencyListAccess().getGroup_4(), "rule__TransformationDependencyList__Group_4__0");
					put(grammarAccess.getTransformationDependencyAccess().getGroup(), "rule__TransformationDependency__Group__0");
					put(grammarAccess.getTransformationDependencyAccess().getGroup_8(), "rule__TransformationDependency__Group_8__0");
					put(grammarAccess.getRuleDependencyDisjunctionAccess().getGroup(), "rule__RuleDependencyDisjunction__Group__0");
					put(grammarAccess.getRuleDependencyDisjunctionAccess().getGroup_1(), "rule__RuleDependencyDisjunction__Group_1__0");
					put(grammarAccess.getRuleDependencyCompositeAccess().getGroup_0(), "rule__RuleDependencyComposite__Group_0__0");
					put(grammarAccess.getRuleDependencyCompositeAccess().getGroup_1(), "rule__RuleDependencyComposite__Group_1__0");
					put(grammarAccess.getRuleDependencyConjunctionAccess().getGroup(), "rule__RuleDependencyConjunction__Group__0");
					put(grammarAccess.getRuleDependencyConjunctionAccess().getGroup_1(), "rule__RuleDependencyConjunction__Group_1__0");
					put(grammarAccess.getRuleDependencyAccess().getGroup(), "rule__RuleDependency__Group__0");
					put(grammarAccess.getRuleDependencyAccess().getGroup_8(), "rule__RuleDependency__Group_8__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getTrcSpecificationAccess().getModuleListAssignment_0(), "rule__TrcSpecification__ModuleListAssignment_0");
					put(grammarAccess.getTrcSpecificationAccess().getTransformationListAssignment_1(), "rule__TrcSpecification__TransformationListAssignment_1");
					put(grammarAccess.getTrcSpecificationAccess().getDependencyListAssignment_2(), "rule__TrcSpecification__DependencyListAssignment_2");
					put(grammarAccess.getTrcRuleAccess().getNameAssignment(), "rule__TrcRule__NameAssignment");
					put(grammarAccess.getModuleListAccess().getModulesAssignment_2(), "rule__ModuleList__ModulesAssignment_2");
					put(grammarAccess.getModuleListAccess().getModulesAssignment_4_0(), "rule__ModuleList__ModulesAssignment_4_0");
					put(grammarAccess.getModuleAccess().getNameAssignment_0(), "rule__Module__NameAssignment_0");
					put(grammarAccess.getModuleAccess().getPathAssignment_2(), "rule__Module__PathAssignment_2");
					put(grammarAccess.getModuleAccess().getRulesAssignment_4_1(), "rule__Module__RulesAssignment_4_1");
					put(grammarAccess.getModuleAccess().getRulesAssignment_4_2_1(), "rule__Module__RulesAssignment_4_2_1");
					put(grammarAccess.getTransformationListAccess().getTransformationsAssignment_2(), "rule__TransformationList__TransformationsAssignment_2");
					put(grammarAccess.getTransformationListAccess().getTransformationsAssignment_3_1(), "rule__TransformationList__TransformationsAssignment_3_1");
					put(grammarAccess.getTransformationAccess().getNameAssignment_0(), "rule__Transformation__NameAssignment_0");
					put(grammarAccess.getTransformationAccess().getModulesAssignment_4(), "rule__Transformation__ModulesAssignment_4");
					put(grammarAccess.getTransformationAccess().getModulesAssignment_5_1(), "rule__Transformation__ModulesAssignment_5_1");
					put(grammarAccess.getTransformationAccess().getImpactsAssignment_6_2(), "rule__Transformation__ImpactsAssignment_6_2");
					put(grammarAccess.getTransformationAccess().getImpactsAssignment_6_3_1(), "rule__Transformation__ImpactsAssignment_6_3_1");
					put(grammarAccess.getTransformationImpactAccess().getQualityAttributeNameAssignment_1_0(), "rule__TransformationImpact__QualityAttributeNameAssignment_1_0");
					put(grammarAccess.getTransformationImpactAccess().getImpactValueAssignment_2(), "rule__TransformationImpact__ImpactValueAssignment_2");
					put(grammarAccess.getTransformationDependencyListAccess().getTransformationDependenciesAssignment_2(), "rule__TransformationDependencyList__TransformationDependenciesAssignment_2");
					put(grammarAccess.getTransformationDependencyListAccess().getTransformationDependenciesAssignment_4_0(), "rule__TransformationDependencyList__TransformationDependenciesAssignment_4_0");
					put(grammarAccess.getTransformationDependencyAccess().getAppliedTransformationAssignment_2(), "rule__TransformationDependency__AppliedTransformationAssignment_2");
					put(grammarAccess.getTransformationDependencyAccess().getAppliedRuleAssignment_4(), "rule__TransformationDependency__AppliedRuleAssignment_4");
					put(grammarAccess.getTransformationDependencyAccess().getVariableIdAssignment_7(), "rule__TransformationDependency__VariableIdAssignment_7");
					put(grammarAccess.getTransformationDependencyAccess().getVariableIdAssignment_8_1(), "rule__TransformationDependency__VariableIdAssignment_8_1");
					put(grammarAccess.getTransformationDependencyAccess().getRequiredTransformationsAssignment_12(), "rule__TransformationDependency__RequiredTransformationsAssignment_12");
					put(grammarAccess.getRuleDependencyDisjunctionAccess().getRequiredTransformationsAssignment_0(), "rule__RuleDependencyDisjunction__RequiredTransformationsAssignment_0");
					put(grammarAccess.getRuleDependencyDisjunctionAccess().getRequiredTransformationsAssignment_1_1(), "rule__RuleDependencyDisjunction__RequiredTransformationsAssignment_1_1");
					put(grammarAccess.getRuleDependencyConjunctionAccess().getRequiredTransformationsAssignment_0(), "rule__RuleDependencyConjunction__RequiredTransformationsAssignment_0");
					put(grammarAccess.getRuleDependencyConjunctionAccess().getRequiredTransformationsAssignment_1_1(), "rule__RuleDependencyConjunction__RequiredTransformationsAssignment_1_1");
					put(grammarAccess.getRuleDependencyAccess().getTypeAssignment_0(), "rule__RuleDependency__TypeAssignment_0");
					put(grammarAccess.getRuleDependencyAccess().getRequiredTransformationAssignment_2(), "rule__RuleDependency__RequiredTransformationAssignment_2");
					put(grammarAccess.getRuleDependencyAccess().getRequiredRuleAssignment_4(), "rule__RuleDependency__RequiredRuleAssignment_4");
					put(grammarAccess.getRuleDependencyAccess().getFieldNamesAssignment_7(), "rule__RuleDependency__FieldNamesAssignment_7");
					put(grammarAccess.getRuleDependencyAccess().getFieldNamesAssignment_8_1(), "rule__RuleDependency__FieldNamesAssignment_8_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			fr.tpt.aadl.ramses.transformation.trc.xtext.ui.contentassist.antlr.internal.InternalTRCParser typedParser = (fr.tpt.aadl.ramses.transformation.trc.xtext.ui.contentassist.antlr.internal.InternalTRCParser) parser;
			typedParser.entryRuleTrcSpecification();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public TRCGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TRCGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
