#ifndef __GENERATED_SUBPROGRAMS_H__
#define __GENERATED_SUBPROGRAMS_H__
#include "arinc653/sampling.h"
#include "arinc653/time.h"
#include "arinc653/types.h"
#include "user_code.h"
#include "gtypes.h"
#include "main.h"
typedef enum {
  test_sampling_refined_model__the_proc1_the_sender_impl_main_state
} test_sampling_refined_model__the_proc1_the_sender_impl_BA_State_t;

void test_sampling_refined_model__the_proc1_the_sender_entrypoint_impl(
	SAMPLING_PORT_ID_TYPE *  cnx_p_out);

typedef enum {
  test_sampling_refined_model__the_proc1_the_sender_entrypoint_impl_BA_entrypoint_init_state,
  test_sampling_refined_model__the_proc1_the_sender_entrypoint_impl_BA_entrypoint_wait_dispatch_state,
  test_sampling_refined_model__the_proc1_the_sender_entrypoint_impl_BA_entrypoint_exec_state,
  test_sampling_refined_model__the_proc1_the_sender_entrypoint_impl_BA_entrypoint_final_state
} test_sampling_refined_model__the_proc1_the_sender_entrypoint_impl_BA_State_t;


#endif

