#ifndef __GENERATED_GTYPES_H__
#define __GENERATED_GTYPES_H__
#include "osek_runtime.h"
#include "toppers_osek/include/kernel.h"
typedef thread_queue_t OSEK_runtime__ThreadQueueType;
typedef StatusType OSEK_runtime__StatusType;
typedef signed int Base_Types__Integer_16;
typedef unsigned int Base_Types__Unsigned_8;
typedef struct __sender_spg_context {
	Base_Types__Unsigned_8 result;
} __sender_spg_context;
typedef enum e_test_osek_eventports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum {
	test_osek_eventports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum_default_behavior
} test_osek_eventports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum;
typedef enum e_test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum {
	test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum_p
} test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum;
typedef  int Base_Types__Integer;
typedef Base_Types__Integer test_osek_eventports_refined_model__the_receiver_p_bufferType[5];
typedef port_queue_t OSEK_runtime__PortQueueType;

#endif

