TARGET = the_proc1_OSEK
TOPPERS_OSEK_OIL_SOURCE = ./the_proc1.oil
TARGET_SOURCES = main.c activity.c subprograms.c gtypes.c deployment.c /home/castella/workspaces/runtime-New_configuration2/eventport/input/user_send.c /home/castella/tools/ramses-install-test/../../../../opt/repositories/ramses-develop/model2model/fr.tpt.aadl.ramses.transformation.atl/aadl_resources/C_runtime/OSEK/osek_runtime.c /home/castella/workspaces/runtime-New_configuration2/eventport/input/user_receive.c 
export USER_INCLUDES=/opt/sandbox/nxtOSEK-ramses /home/castella/workspaces/runtime-New_configuration2/eventport/input /home/castella/workspaces/runtime-New_configuration2/eventport/input/instances /home/castella/workspaces/runtime-New_configuration2/eventport /home/castella/tools/ramses-install-test/../../../../opt/repositories/ramses-develop/model2model/fr.tpt.aadl.ramses.transformation.atl/aadl_resources/C_runtime/PeriodicDelayed_runtime /home/castella/tools/ramses-install-test/../../../../opt/repositories/ramses-develop/model2model/fr.tpt.aadl.ramses.transformation.atl/aadl_resources/C_runtime/OSEK 
O_PATH ?= build
include /opt/sandbox/nxtOSEK-ramses/ecrobot/ecrobot.mak
