#ifndef __GENERATED_GTYPES_H__
#define __GENERATED_GTYPES_H__
#include "kernel.h"
typedef enum e_nxtTypes__nxt_sensor_port {
	nxtTypes__nxt_sensor_port_NXT_PORT_S1,
	nxtTypes__nxt_sensor_port_NXT_PORT_S2,
	nxtTypes__nxt_sensor_port_NXT_PORT_S3,
	nxtTypes__nxt_sensor_port_NXT_PORT_S4
} nxtTypes__nxt_sensor_port;
typedef StatusType OSEK_runtime__StatusType;
typedef enum e_colorTypes__color_id {
	colorTypes__color_id_NXT_COLOR_BLACK,
	colorTypes__color_id_NXT_COLOR_BLUE,
	colorTypes__color_id_NXT_COLOR_GREEN,
	colorTypes__color_id_NXT_COLOR_YELLOW,
	colorTypes__color_id_NXT_COLOR_ORANGE,
	colorTypes__color_id_NXT_COLOR_RED,
	colorTypes__color_id_NXT_COLOR_WHITE,
	colorTypes__color_id_NXT_COLOR_UNKNOWN
} colorTypes__color_id;
typedef enum e_test_osek_dataports_refined_model__the_proc_the_sender_behaviorIdentifier_enum {
	test_osek_dataports_refined_model__the_proc_the_sender_behaviorIdentifier_enum_default_behavior
} test_osek_dataports_refined_model__the_proc_the_sender_behaviorIdentifier_enum;
typedef enum e_test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum {
	test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum_p
} test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum;
typedef enum e_test_osek_eventdataports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum {
	test_osek_eventdataports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum_default_behavior
} test_osek_eventdataports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum;
typedef enum e_test_osek_eventdataports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum {
	test_osek_eventdataports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_osek_eventdataports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum_p
} test_osek_eventdataports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum;
typedef enum e_test_osek_eventports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum {
	test_osek_eventports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum_default_behavior
} test_osek_eventports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum;
typedef enum e_test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum {
	test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum_p
} test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum;
typedef enum e_motorTest_refined_model__proces_th_behaviorIdentifier_enum {
	motorTest_refined_model__proces_th_behaviorIdentifier_enum_default_behavior
} motorTest_refined_model__proces_th_behaviorIdentifier_enum;
typedef enum e_readColor_refined_model__proces_th_behaviorIdentifier_enum {
	readColor_refined_model__proces_th_behaviorIdentifier_enum_default_behavior
} readColor_refined_model__proces_th_behaviorIdentifier_enum;
typedef enum e_readColor_refined_model__proces_bg_behaviorIdentifier_enum {
	readColor_refined_model__proces_bg_behaviorIdentifier_enum_default_behavior
} readColor_refined_model__proces_bg_behaviorIdentifier_enum;

#endif

