/**
 * generated by Xtext
 */
package fr.tpt.aadl.ramses.transformation.trc.xtext.ui.contentassist;

import fr.tpt.aadl.ramses.transformation.trc.xtext.ui.contentassist.AbstractTRCProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class TRCProposalProvider extends AbstractTRCProposalProvider {
}
