/*
* generated by Xtext
*/
package fr.tpt.aadl.ramses.transformation.trc.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.tpt.aadl.ramses.transformation.trc.xtext.services.TRCGrammarAccess;

public class TRCParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TRCGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.tpt.aadl.ramses.transformation.trc.xtext.parser.antlr.internal.InternalTRCParser createParser(XtextTokenStream stream) {
		return new fr.tpt.aadl.ramses.transformation.trc.xtext.parser.antlr.internal.InternalTRCParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TrcSpecification";
	}
	
	public TRCGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TRCGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
