/*
 * generated by Xtext
 */
package fr.tpt.aadl.ramses.transformation.trc.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TRCRuntimeModule extends fr.tpt.aadl.ramses.transformation.trc.xtext.AbstractTRCRuntimeModule {

}
