<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hooks" nsURI="http://fr.tpt.aadl.ramses.transformation.atl.launch"
    nsPrefix="hooks">
  <eClassifiers xsi:type="ecore:EClass" name="HookAccess">
    <eOperations name="orderFeatures" upperBound="-1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//Feature">
      <eParameters name="cpt" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//ComponentType"/>
    </eOperations>
    <eOperations name="copyLocationReference">
      <eParameters name="target" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//Element"/>
      <eParameters name="source" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//Element"/>
    </eOperations>
    <eOperations name="addTransformationBackTrace" lowerBound="1">
      <eParameters name="targetDeclarative" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//NamedElement"/>
      <eParameters name="sourceInstance" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//NamedElement"/>
    </eOperations>
    <eOperations name="putTransitionWhereSrc" lowerBound="1">
      <eParameters name="state" lowerBound="1" eType="ecore:EClass ../../org.osate.ba/model/aadlba.ecore#//BehaviorState"/>
      <eParameters name="transition" lowerBound="1" eType="ecore:EClass ../../org.osate.ba/model/aadlba.ecore#//BehaviorTransition"/>
    </eOperations>
    <eOperations name="getCurrentPerionReadTable" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eParameters name="port" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//FeatureInstance"/>
    </eOperations>
    <eOperations name="getCurrentDeadlineWriteTable" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eParameters name="port" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//FeatureInstance"/>
      <eParameters name="destinationPort" eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//FeatureInstance"/>
    </eOperations>
    <eOperations name="getBufferSize" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eParameters name="destinationFeatureInstance" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//FeatureInstance"/>
    </eOperations>
    <eOperations name="setDirection" lowerBound="1">
      <eParameters name="feature" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//DirectedFeature"/>
      <eParameters name="direction" eType="ecore:EDataType ../../org.osate.ba/model/aadlba.ecore#//String"/>
    </eOperations>
    <eOperations name="isUsedInSpecialOperator" lowerBound="1" eType="ecore:EDataType ../../org.osate.aadl2/model/aadl2.ecore#//Boolean">
      <eParameters name="ba" lowerBound="1" eType="ecore:EClass ../../org.osate.ba/model/aadlba.ecore#//BehaviorAnnex"/>
      <eParameters name="p" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//Port"/>
      <eParameters name="operatorName" lowerBound="1" eType="ecore:EDataType ../../org.osate.aadl2/model/aadl2.ecore#//String"/>
    </eOperations>
    <eOperations name="getHyperperiod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eParameters name="port" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//FeatureInstance"/>
    </eOperations>
    <eOperations name="getTimingPrecision" lowerBound="1" eType="ecore:EDataType ../../org.osate.aadl2/model/aadl2.ecore#//String">
      <eParameters name="namedElement" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//NamedElement"/>
    </eOperations>
    <eOperations name="getListOfPath" upperBound="-1" eType="ecore:EDataType ../../org.osate.aadl2/model/aadl2.ecore#//String">
      <eParameters name="pa" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//PropertyAssociation"/>
    </eOperations>
    <eOperations name="allPortCount" upperBound="-1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//Port">
      <eParameters name="e" lowerBound="1" eType="ecore:EClass ../../org.osate.ba/model/aadlba.ecore#//BehaviorElement"/>
    </eOperations>
    <eOperations name="getStringLiteral" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//StringLiteral">
      <eParameters name="pa" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//PropertyAssociation"/>
      <eParameters name="stringLiteralValue" lowerBound="1" eType="ecore:EDataType ../../org.osate.aadl2/model/aadl2.ecore#//String"/>
    </eOperations>
    <eOperations name="getEnumerators" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//PropertyAssociation">
      <eParameters name="classifier" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//Classifier"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
