echo Executing NeXTTool to upload /opt/sandbox/nxtOSEK-ramses/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
wineconsole /cygdrive/C/cygwin/nexttool/NeXTTool.exe /COM=usb -firmware=/opt/sandbox/nxtOSEK-ramses/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
