#ifndef __GENERATED_GTYPES_H__
#define __GENERATED_GTYPES_H__
#include "ecrobot/c/ecrobot_interface.h"
#include "toppers_osek/include/kernel.h"
typedef enum e_nxtTypes__nxt_sensor_port {
	nxtTypes__nxt_sensor_port_NXT_PORT_S1,
	nxtTypes__nxt_sensor_port_NXT_PORT_S2,
	nxtTypes__nxt_sensor_port_NXT_PORT_S3,
	nxtTypes__nxt_sensor_port_NXT_PORT_S4
} nxtTypes__nxt_sensor_port;
typedef StatusType OSEK_runtime__StatusType;
typedef S32 nxtTypes__S32;
typedef enum e_sonarTest_refined_model__proces_th_behaviorIdentifier_enum {
	sonarTest_refined_model__proces_th_behaviorIdentifier_enum_default_behavior
} sonarTest_refined_model__proces_th_behaviorIdentifier_enum;

#endif

