#include "activity.h"
#include "main.h"

extern SAMPLING_PORT_ID_TYPE train_inst_trainPpu_inst_trainDataInglobalVariable;
extern BLACKBOARD_ID_TYPE VobcTrainPositionEstimation_vobcTrainPositionEstimation_wheelAngleIn_globalVariable;
extern cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_currentState TrainPpu_odometerAcquisitionParent_BA_currentState;
void* cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_impl_Job()
{
  Base_Types__Integer_16 cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_impl_trainDataIn_persistentFreshnessIndicator = 0;
  Base_Types__Integer_16 cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_impl_wheelAngleOut_persistentFreshnessIndicator = 0;
  cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl (&train_inst_trainPpu_inst_trainDataInglobalVariable, &VobcTrainPositionEstimation_vobcTrainPositionEstimation_wheelAngleIn_globalVariable, &TrainPpu_odometerAcquisitionParent_BA_currentState, &cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_impl_trainDataIn_persistentFreshnessIndicator, &cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_impl_wheelAngleOut_persistentFreshnessIndicator);
  return 0;
}
extern BLACKBOARD_ID_TYPE TrainPpu_trainTraction_tractionIn_globalVariable;
extern SAMPLING_PORT_ID_TYPE train_inst_trainPpu_inst_trainDataInglobalVariable;
extern BLACKBOARD_ID_TYPE VobcTrainPositionEstimation_vobcTrainPositionEstimation_additionalTrainPositionOffset_globalVariable;
extern SAMPLING_PORT_ID_TYPE train_inst_trainPpu_inst_trainDataOut_globalVariable;
extern cbtc_refined_model__train_inst_TrainPpu_trainTraction_currentState TrainPpu_trainTractionParent_BA_currentState;
void* cbtc_refined_model__train_inst_TrainPpu_trainTraction_impl_Job()
{
  Base_Types__Integer_16 cbtc_refined_model__train_inst_TrainPpu_trainTraction_impl_tractionIn_persistentFreshnessIndicator = 0;
  Base_Types__Integer_16 cbtc_refined_model__train_inst_TrainPpu_trainTraction_impl_trainDataIn_persistentFreshnessIndicator = 0;
  cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl (&TrainPpu_trainTraction_tractionIn_globalVariable, &train_inst_trainPpu_inst_trainDataInglobalVariable, &VobcTrainPositionEstimation_vobcTrainPositionEstimation_additionalTrainPositionOffset_globalVariable, &train_inst_trainPpu_inst_trainDataOut_globalVariable, &TrainPpu_trainTractionParent_BA_currentState, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_impl_tractionIn_persistentFreshnessIndicator, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_impl_trainDataIn_persistentFreshnessIndicator);
  return 0;
}
extern BLACKBOARD_ID_TYPE VobcTrainPositionEstimation_vobcTrainPositionEstimation_additionalTrainPositionOffset_globalVariable;
extern BLACKBOARD_ID_TYPE VobcTrainPositionEstimation_vobcTrainPositionEstimation_wheelAngleIn_globalVariable;
extern BLACKBOARD_ID_TYPE TrainSpeedAccelCompute_trainSpeedAccelCompute_trainPositionIn_globalVariable;
extern cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_currentState VobcTrainPositionEstimation_vobcTrainPositionEstimationParent_BA_currentState;
void* cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_impl_Job()
{
  Base_Types__Integer_16 cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_impl_wheelAngleIn_persistentFreshnessIndicator = 0;
  Base_Types__Integer_16 cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_impl_trainPositionOut_F_persistentFreshnessIndicator = 0;
  cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl (&VobcTrainPositionEstimation_vobcTrainPositionEstimation_additionalTrainPositionOffset_globalVariable, &VobcTrainPositionEstimation_vobcTrainPositionEstimation_wheelAngleIn_globalVariable, &TrainSpeedAccelCompute_trainSpeedAccelCompute_trainPositionIn_globalVariable, &VobcTrainPositionEstimation_vobcTrainPositionEstimationParent_BA_currentState, &cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_impl_wheelAngleIn_persistentFreshnessIndicator, &cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_impl_trainPositionOut_F_persistentFreshnessIndicator);
  return 0;
}
extern SAMPLING_PORT_ID_TYPE train_inst_TrainSpeedAccelCompute_inst_eoaInglobalVariable;
extern BLACKBOARD_ID_TYPE TrainSpeedAccelCompute_trainSpeedAccelCompute_trainPositionIn_globalVariable;
extern SAMPLING_PORT_ID_TYPE train_inst_TrainSpeedAccelCompute_inst_trainPositionForMauOut_globalVariable;
extern BLACKBOARD_ID_TYPE TrainPpu_trainTraction_tractionIn_globalVariable;
extern cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_currentState TrainSpeedAccelCompute_trainSpeedAccelComputeParent_BA_currentState;
void* cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_impl_Job()
{
  Base_Types__Integer_16 cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_impl_eoaIn_persistentFreshnessIndicator = 0;
  Base_Types__Integer_16 cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_impl_trainPositionIn_persistentFreshnessIndicator = 0;
  Base_Types__Integer_16 cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_impl_trainPositionForMauOut_persistentFreshnessIndicator = 0;
  Base_Types__Integer_16 cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_impl_tractionOut_persistentFreshnessIndicator = 0;
  cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl (&train_inst_TrainSpeedAccelCompute_inst_eoaInglobalVariable, &TrainSpeedAccelCompute_trainSpeedAccelCompute_trainPositionIn_globalVariable, &train_inst_TrainSpeedAccelCompute_inst_trainPositionForMauOut_globalVariable, &TrainPpu_trainTraction_tractionIn_globalVariable, &TrainSpeedAccelCompute_trainSpeedAccelComputeParent_BA_currentState, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_impl_eoaIn_persistentFreshnessIndicator, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_impl_trainPositionIn_persistentFreshnessIndicator, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_impl_trainPositionForMauOut_persistentFreshnessIndicator, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_impl_tractionOut_persistentFreshnessIndicator);
  return 0;
}
