#include "deployment.h"
BLACKBOARD_ID_TYPE TrainPpu_trainTraction_tractionIn_globalVariable;
BLACKBOARD_ID_TYPE VobcTrainPositionEstimation_vobcTrainPositionEstimation_additionalTrainPositionOffset_globalVariable;
SAMPLING_PORT_ID_TYPE train_inst_trainPpu_inst_trainDataInglobalVariable;
BLACKBOARD_ID_TYPE VobcTrainPositionEstimation_vobcTrainPositionEstimation_wheelAngleIn_globalVariable;
SAMPLING_PORT_ID_TYPE train_inst_TrainSpeedAccelCompute_inst_trainPositionForMauOut_globalVariable;
cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_currentState TrainSpeedAccelCompute_trainSpeedAccelComputeParent_BA_currentState = cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_currentState_switch;
cbtc_refined_model__train_inst_TrainPpu_trainTraction_currentState TrainPpu_trainTractionParent_BA_currentState = cbtc_refined_model__train_inst_TrainPpu_trainTraction_currentState_switch;
SAMPLING_PORT_ID_TYPE train_inst_trainPpu_inst_trainDataOut_globalVariable;
SAMPLING_PORT_ID_TYPE train_inst_TrainSpeedAccelCompute_inst_eoaInglobalVariable;
cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_currentState VobcTrainPositionEstimation_vobcTrainPositionEstimationParent_BA_currentState = cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_currentState_switch;
BLACKBOARD_ID_TYPE TrainSpeedAccelCompute_trainSpeedAccelCompute_trainPositionIn_globalVariable;
cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_currentState TrainPpu_odometerAcquisitionParent_BA_currentState = cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_currentState_switch;
