#include "arinc653/sampling.h"
#include "business-code/cbtc_module.h"
#include "arinc653/blackboard.h"
#include "subprograms.h"
cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_BA_State_t train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_BA_entrypoint_init_state;
void cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl(
	SAMPLING_PORT_ID_TYPE *  trainDataIn,
	BLACKBOARD_ID_TYPE *  PortCnx1_wheelAngleOut,
	cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_currentState *  Parent_BA_currentState_Access,
	Base_Types__Integer_16 *  trainDataIn_freshnessIndicator_access,
	Base_Types__Integer_16 *  wheelAngleOut_freshnessIndicator_access)
{
  cbtc_refined_model__TrainData_freshness_t_impl cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_trainDataIn_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_trainDataIn_Length = sizeof(cbtc_refined_model__TrainData_freshness_t_impl);
  cbtc_refined_model__OdometerData_freshness_t_impl cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_wheelAngleOut_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_wheelAngleOut_Length = sizeof(cbtc_refined_model__OdometerData_freshness_t_impl);
  RETURN_CODE_TYPE cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_trainDataIn_ErrorCode = 0;
  VALIDITY_TYPE cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_trainDataIn_Validity;
  RETURN_CODE_TYPE cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_train_inst_TrainPpu_odometerAcquisition_runtime_call_ret;
  OdometerData odometerOut;
OdometerData odometerIn;
cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_behaviorIdentifier_enum whichPortActivated = cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_current_state)
  {
    case cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_train_inst_TrainPpu_odometerAcquisition_runtime_call_ret);
      break;
    }
    case cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_behaviorIdentifier_enum_default_behavior)
    {
      train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_currentState_switch) {
      READ_SAMPLING_MESSAGE ((*trainDataIn), &cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_trainDataIn_localVariable, cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_trainDataIn_Length, &cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_trainDataIn_Validity, &cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_train_inst_TrainPpu_odometerAcquisition_runtime_call_ret);
      if ((cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_trainDataIn_localVariable.fresh_ba != trainDataIn_freshnessIndicator_access)) {
      TrainPpu_odometerAcquisition (&cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_trainDataIn_localVariable.pvalue, &odometerOut);
      odometerIn = odometerOut;
      WheelAngleAcquisition_wheelAngleAcquisition (&odometerIn, &(cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_wheelAngleOut_localVariable.pvalue));
      }
      trainDataIn_freshnessIndicator_access = cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_trainDataIn_localVariable.fresh_ba;
      wheelAngleOut_freshnessIndicator_access = wheelAngleOut_freshnessIndicator_access + 1;
      cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_wheelAngleOut_localVariable.fresh_ba = wheelAngleOut_freshnessIndicator_access;
      (*Parent_BA_currentState_Access) = cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_currentState_switch;
      DISPLAY_BLACKBOARD ((*PortCnx1_wheelAngleOut), &cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_wheelAngleOut_localVariable, cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_wheelAngleOut_Length, &cbtc_refined_model__train_inst_TrainPpu_odometerAcquisition_entrypoint_impl_train_inst_TrainPpu_odometerAcquisition_runtime_call_ret);
      }
      break;
    }
  }
}
}
cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_BA_State_t train_inst_TrainPpu_trainTraction_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_BA_entrypoint_init_state;
void cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl(
	BLACKBOARD_ID_TYPE *  tractionIn,
	SAMPLING_PORT_ID_TYPE *  trainDataIn,
	BLACKBOARD_ID_TYPE *  PortCnx2_additionalTrainPositionOffset,
	SAMPLING_PORT_ID_TYPE *  PortCnx9_trainDataOut,
	cbtc_refined_model__train_inst_TrainPpu_trainTraction_currentState *  Parent_BA_currentState_Access,
	Base_Types__Integer_16 *  tractionIn_freshnessIndicator_access,
	Base_Types__Integer_16 *  trainDataIn_freshnessIndicator_access)
{
  cbtc_refined_model__TractionData_freshness_t_impl cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_tractionIn_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_tractionIn_Length = sizeof(cbtc_refined_model__TractionData_freshness_t_impl);
  cbtc_refined_model__TrainData_freshness_t_impl cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataIn_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataIn_Length = sizeof(cbtc_refined_model__TrainData_freshness_t_impl);
  TrainPositionOffset cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_additionalTrainPositionOffset_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_additionalTrainPositionOffset_Length = sizeof(TrainPositionOffset);
  TrainData cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataOut_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataOut_Length = sizeof(TrainData);
  RETURN_CODE_TYPE cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_tractionIn_ErrorCode = 0;
  RETURN_CODE_TYPE cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataIn_ErrorCode = 0;
  VALIDITY_TYPE cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataIn_Validity;
  SYSTEM_TIME_TYPE cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_tractionIn_TimeOut = 0;
  RETURN_CODE_TYPE cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_train_inst_TrainPpu_trainTraction_runtime_call_ret;
  cbtc_refined_model__train_inst_TrainPpu_trainTraction_behaviorIdentifier_enum whichPortActivated = cbtc_refined_model__train_inst_TrainPpu_trainTraction_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(train_inst_TrainPpu_trainTraction_entrypoint_impl_current_state)
  {
    case cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      train_inst_TrainPpu_trainTraction_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = cbtc_refined_model__train_inst_TrainPpu_trainTraction_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      train_inst_TrainPpu_trainTraction_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_train_inst_TrainPpu_trainTraction_runtime_call_ret);
      break;
    }
    case cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == cbtc_refined_model__train_inst_TrainPpu_trainTraction_behaviorIdentifier_enum_default_behavior)
    {
      train_inst_TrainPpu_trainTraction_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == cbtc_refined_model__train_inst_TrainPpu_trainTraction_currentState_switch) {
      READ_BLACKBOARD ((*tractionIn), cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_tractionIn_TimeOut, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_tractionIn_localVariable, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_tractionIn_Length, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_train_inst_TrainPpu_trainTraction_runtime_call_ret);
      READ_SAMPLING_MESSAGE ((*trainDataIn), &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataIn_localVariable, cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataIn_Length, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataIn_Validity, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_train_inst_TrainPpu_trainTraction_runtime_call_ret);
      if ((cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_tractionIn_localVariable.fresh_ba != tractionIn_freshnessIndicator_access) && (cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataIn_localVariable.fresh_ba != trainDataIn_freshnessIndicator_access)) {
      TrainPpu_trainTraction (&cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_tractionIn_localVariable.pvalue, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataIn_localVariable.pvalue, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_additionalTrainPositionOffset_localVariable, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataOut_localVariable);
      }
      tractionIn_freshnessIndicator_access = cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_tractionIn_localVariable.fresh_ba;
      trainDataIn_freshnessIndicator_access = cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataIn_localVariable.fresh_ba;
      (*Parent_BA_currentState_Access) = cbtc_refined_model__train_inst_TrainPpu_trainTraction_currentState_switch;
      DISPLAY_BLACKBOARD ((*PortCnx2_additionalTrainPositionOffset), &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_additionalTrainPositionOffset_localVariable, cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_additionalTrainPositionOffset_Length, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_train_inst_TrainPpu_trainTraction_runtime_call_ret);
      WRITE_SAMPLING_MESSAGE ((*PortCnx9_trainDataOut), &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataOut_localVariable, cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_trainDataOut_Length, &cbtc_refined_model__train_inst_TrainPpu_trainTraction_entrypoint_impl_train_inst_TrainPpu_trainTraction_runtime_call_ret);
      }
      break;
    }
  }
}
}
cbtc__VobcTrainPositionEstimation_delayed_additionalTrainPositionOffset_BA_State_t VobcTrainPositionEstimation_delayed_additionalTrainPositionOffset_current_state = cbtc__VobcTrainPositionEstimation_delayed_additionalTrainPositionOffset_s;
void cbtc__VobcTrainPositionEstimation_delayed_additionalTrainPositionOffset(
	TrainPositionOffset *  additionalTrainPositionOffset,
	TrainPositionOffset *  delayed_additionalTrainPositionOffset)
{
  while(1)
{
  switch(VobcTrainPositionEstimation_delayed_additionalTrainPositionOffset_current_state)
  {
    case cbtc__VobcTrainPositionEstimation_delayed_additionalTrainPositionOffset_s:
    // Transition id: t
    if(1) // no execution condition
    {
      VobcTrainPositionEstimation_delayed_additionalTrainPositionOffset_current_state = cbtc__VobcTrainPositionEstimation_delayed_additionalTrainPositionOffset_s;
      (*delayed_additionalTrainPositionOffset) = (*additionalTrainPositionOffset);
      return;
    }
  }
}
}
cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_BA_State_t train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_current_state = cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_BA_entrypoint_init_state;
void cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl(
	BLACKBOARD_ID_TYPE *  additionalTrainPositionOffset,
	BLACKBOARD_ID_TYPE *  wheelAngleIn,
	BLACKBOARD_ID_TYPE *  PortCnx3_trainPositionOut_F,
	cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_currentState *  Parent_BA_currentState_Access,
	Base_Types__Integer_16 *  wheelAngleIn_freshnessIndicator_access,
	Base_Types__Integer_16 *  trainPositionOut_F_freshnessIndicator_access)
{
  TrainPositionOffset cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_additionalTrainPositionOffset_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_additionalTrainPositionOffset_Length = sizeof(TrainPositionOffset);
  cbtc_refined_model__OdometerData_freshness_t_impl cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_wheelAngleIn_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_wheelAngleIn_Length = sizeof(cbtc_refined_model__OdometerData_freshness_t_impl);
  cbtc_refined_model__VobcData_freshness_t_impl cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_trainPositionOut_F_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_trainPositionOut_F_Length = sizeof(cbtc_refined_model__VobcData_freshness_t_impl);
  RETURN_CODE_TYPE cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_additionalTrainPositionOffset_ErrorCode = 0;
  RETURN_CODE_TYPE cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_wheelAngleIn_ErrorCode = 0;
  SYSTEM_TIME_TYPE cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_additionalTrainPositionOffset_TimeOut = 0;
  SYSTEM_TIME_TYPE cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_wheelAngleIn_TimeOut = 0;
  RETURN_CODE_TYPE cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_runtime_call_ret;
  TrainPositionOffset delayed_additionalTrainPositionOffset;
VobcData trainPositionOut;
VobcData trainPositionIn;
cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_behaviorIdentifier_enum whichPortActivated = cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_current_state)
  {
    case cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_current_state = cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_current_state = cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_runtime_call_ret);
      break;
    }
    case cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_behaviorIdentifier_enum_default_behavior)
    {
      train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_current_state = cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_currentState_switch) {
      READ_BLACKBOARD ((*additionalTrainPositionOffset), cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_additionalTrainPositionOffset_TimeOut, &cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_additionalTrainPositionOffset_localVariable, &cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_additionalTrainPositionOffset_Length, &cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_runtime_call_ret);
      READ_BLACKBOARD ((*wheelAngleIn), cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_wheelAngleIn_TimeOut, &cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_wheelAngleIn_localVariable, &cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_wheelAngleIn_Length, &cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_runtime_call_ret);
      cbtc__VobcTrainPositionEstimation_delayed_additionalTrainPositionOffset (&cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_additionalTrainPositionOffset_localVariable, &delayed_additionalTrainPositionOffset);
      if ((cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_wheelAngleIn_localVariable.fresh_ba != wheelAngleIn_freshnessIndicator_access)) {
      VobcTrainPositionEstimation_vobcTrainPositionEstimation (&cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_wheelAngleIn_localVariable.pvalue, &delayed_additionalTrainPositionOffset, &trainPositionOut);
      trainPositionIn = trainPositionOut;
      VobcTrainPositionSending_vobcTrainPositionSending (&trainPositionIn, &(cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_trainPositionOut_F_localVariable.pvalue));
      }
      wheelAngleIn_freshnessIndicator_access = cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_wheelAngleIn_localVariable.fresh_ba;
      trainPositionOut_F_freshnessIndicator_access = trainPositionOut_F_freshnessIndicator_access + 1;
      cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_trainPositionOut_F_localVariable.fresh_ba = trainPositionOut_F_freshnessIndicator_access;
      (*Parent_BA_currentState_Access) = cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_currentState_switch;
      DISPLAY_BLACKBOARD ((*PortCnx3_trainPositionOut_F), &cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_trainPositionOut_F_localVariable, cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_trainPositionOut_F_Length, &cbtc_refined_model__train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_entrypoint_impl_train_inst_VobcTrainPositionEstimation_vobcTrainPositionEstimation_runtime_call_ret);
      }
      break;
    }
  }
}
}
cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_BA_State_t train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_BA_entrypoint_init_state;
void cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl(
	SAMPLING_PORT_ID_TYPE *  eoaIn,
	BLACKBOARD_ID_TYPE *  trainPositionIn,
	SAMPLING_PORT_ID_TYPE *  PortCnx8_trainPositionForMauOut,
	BLACKBOARD_ID_TYPE *  PortCnx4_tractionOut,
	cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_currentState *  Parent_BA_currentState_Access,
	Base_Types__Integer_16 *  eoaIn_freshnessIndicator_access,
	Base_Types__Integer_16 *  trainPositionIn_freshnessIndicator_access,
	Base_Types__Integer_16 *  trainPositionForMauOut_freshnessIndicator_access,
	Base_Types__Integer_16 *  tractionOut_freshnessIndicator_access)
{
  cbtc_refined_model__EndOfAuthority_freshness_t_impl cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_eoaIn_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_eoaIn_Length = sizeof(cbtc_refined_model__EndOfAuthority_freshness_t_impl);
  cbtc_refined_model__VobcData_freshness_t_impl cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionIn_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionIn_Length = sizeof(cbtc_refined_model__VobcData_freshness_t_impl);
  cbtc_refined_model__VobcData_freshness_t_impl cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionForMauOut_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionForMauOut_Length = sizeof(cbtc_refined_model__VobcData_freshness_t_impl);
  cbtc_refined_model__TractionData_freshness_t_impl cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_tractionOut_localVariable;
  MESSAGE_SIZE_TYPE cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_tractionOut_Length = sizeof(cbtc_refined_model__TractionData_freshness_t_impl);
  RETURN_CODE_TYPE cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_eoaIn_ErrorCode = 0;
  RETURN_CODE_TYPE cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionIn_ErrorCode = 0;
  VALIDITY_TYPE cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_eoaIn_Validity;
  SYSTEM_TIME_TYPE cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionIn_TimeOut = 0;
  RETURN_CODE_TYPE cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_runtime_call_ret;
  TractionData trainAccelOut;
TractionData trainAccelIn;
cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_behaviorIdentifier_enum whichPortActivated = cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_current_state)
  {
    case cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_runtime_call_ret);
      break;
    }
    case cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_behaviorIdentifier_enum_default_behavior)
    {
      train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_current_state = cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_currentState_switch) {
      READ_SAMPLING_MESSAGE ((*eoaIn), &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_eoaIn_localVariable, cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_eoaIn_Length, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_eoaIn_Validity, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_runtime_call_ret);
      READ_BLACKBOARD ((*trainPositionIn), cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionIn_TimeOut, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionIn_localVariable, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionIn_Length, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_runtime_call_ret);
      if ((cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_eoaIn_localVariable.fresh_ba != eoaIn_freshnessIndicator_access) && (cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionIn_localVariable.fresh_ba != trainPositionIn_freshnessIndicator_access)) {
      TrainSpeedAccelCompute_trainSpeedAccelCompute (&cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_eoaIn_localVariable.pvalue, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionIn_localVariable.pvalue, &trainAccelOut, &(cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionForMauOut_localVariable.pvalue));
      trainAccelIn = trainAccelOut;
      AccelerationSending_accelerationSending (&trainAccelIn, &(cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_tractionOut_localVariable.pvalue));
      }
      eoaIn_freshnessIndicator_access = cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_eoaIn_localVariable.fresh_ba;
      trainPositionIn_freshnessIndicator_access = cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionIn_localVariable.fresh_ba;
      trainPositionForMauOut_freshnessIndicator_access = trainPositionForMauOut_freshnessIndicator_access + 1;
      cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionForMauOut_localVariable.fresh_ba = trainPositionForMauOut_freshnessIndicator_access;
      tractionOut_freshnessIndicator_access = tractionOut_freshnessIndicator_access + 1;
      cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_tractionOut_localVariable.fresh_ba = tractionOut_freshnessIndicator_access;
      (*Parent_BA_currentState_Access) = cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_currentState_switch;
      WRITE_SAMPLING_MESSAGE ((*PortCnx8_trainPositionForMauOut), &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionForMauOut_localVariable, cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_trainPositionForMauOut_Length, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_runtime_call_ret);
      DISPLAY_BLACKBOARD ((*PortCnx4_tractionOut), &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_tractionOut_localVariable, cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_tractionOut_Length, &cbtc_refined_model__train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_entrypoint_impl_train_inst_TrainSpeedAccelCompute_trainSpeedAccelCompute_runtime_call_ret);
      }
      break;
    }
  }
}
}
