#ifndef __GENERATED_GTYPES_H__
#define __GENERATED_GTYPES_H__
#include "osek_runtime.h"
#include "kernel.h"
typedef data_port_t OSEK_runtime__DataPortType;
typedef StatusType OSEK_runtime__StatusType;
typedef  int test_osek_dataports__Integer;
typedef signed int Base_Types__Integer_16;
typedef enum e_test_osek_dataports_refined_model__the_proc_the_sender_behaviorIdentifier_enum {
	test_osek_dataports_refined_model__the_proc_the_sender_behaviorIdentifier_enum_default_behavior
} test_osek_dataports_refined_model__the_proc_the_sender_behaviorIdentifier_enum;
typedef enum e_test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum {
	test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum_p
} test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum;

#endif

