#include "arinc653/queueing.h"
#include "types.h"
#include "subprograms.h"
test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_BA_State_t the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_init_state;
void test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl(
	Base_Types__Unsigned_32 *  the_proc2_p_in_comConnectionLength_len,
	pok_port_id_t *  the_proc2_p_in_comConnectionPortId_port_id,
	APEX_INTEGER *  the_proc2_p_in_cnx_p_in)
{
  RETURN_CODE_TYPE test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_the_cpu2_system_part_comProcess_system_part_comm_runtime_call_ret;
  common_pkg__Integer test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_p_in_localVariable;
  SYSTEM_TIME_TYPE test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_p_in_TimeOut = 0;
  test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_behaviorIdentifier_enum whichPortActivated = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_current_state)
  {
    case test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_the_cpu2_system_part_comProcess_system_part_comm_runtime_call_ret);
      break;
    }
    case test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: the_cpu2_communicationCallSequence -- Priority 0
    if(whichPortActivated == test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_behaviorIdentifier_enum_default_behavior)
    {
      the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      rtl8029_read (*the_proc2_p_in_comConnectionPortId_port_id, &test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_p_in_localVariable, *the_proc2_p_in_comConnectionLength_len);
      SEND_QUEUING_MESSAGE ((*the_proc2_p_in_cnx_p_in), &test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_p_in_localVariable, *the_proc2_p_in_comConnectionLength_len, test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_p_in_TimeOut, &test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_system_part_comm_entrypoint_impl_the_cpu2_system_part_comProcess_system_part_comm_runtime_call_ret);
      break;
    }
  }
}
}
test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_BA_State_t the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_BA_entrypoint_init_state;
void test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl()
{
  RETURN_CODE_TYPE test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_runtime_call_ret;
  test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_behaviorIdentifier_enum whichPortActivated = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_current_state)
  {
    case test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_runtime_call_ret);
      break;
    }
    case test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: system_part_pollCallSequence -- Priority 0
    if(whichPortActivated == test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_behaviorIdentifier_enum_default_behavior)
    {
      the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu2_system_part_comProcess_the_cpu2_system_part_comm_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      rtl8029_polling ();
      break;
    }
  }
}
}
