#ifndef __GENERATED_GTYPES_H__
#define __GENERATED_GTYPES_H__
#include "arinc653/types.h"
typedef signed int Base_Types__Integer_16;
typedef Base_Types__Integer_16 test_buffer_delayed_refined_model__bufferArrayImpl_the_receiver_p_in_impl[6];
typedef unsigned int Base_Types__Unsigned_16;
typedef struct PeriodicDelayed_runtime__component_instance_t_impl {
	Base_Types__Unsigned_16 period;
	Base_Types__Unsigned_16 deadline;
} PeriodicDelayed_runtime__component_instance_t_impl;
typedef PeriodicDelayed_runtime__component_instance_t_impl test_buffer_delayed_refined_model__ComponentInstanceArrayDataType_the_receiver_p_in[1];
typedef struct test_buffer_delayed_refined_model__periodic_delayed_context_t_impl_the_proc_the_receiver_p_in {
	Base_Types__Unsigned_16 reader_task_period;
	Base_Types__Unsigned_16 writer_count;
	Base_Types__Unsigned_16 buffer_size;
	Base_Types__Unsigned_16 hyperperiod;
	test_buffer_delayed_refined_model__ComponentInstanceArrayDataType_the_receiver_p_in writer_instances;
} test_buffer_delayed_refined_model__periodic_delayed_context_t_impl_the_proc_the_receiver_p_in;
typedef RETURN_CODE_TYPE arinc653_runtime__Return_Code_Type;
typedef  int common_pkg__Integer;
typedef enum e_test_buffer_delayed_refined_model__the_proc_the_sender_behaviorIdentifier_enum {
	test_buffer_delayed_refined_model__the_proc_the_sender_behaviorIdentifier_enum_default_behavior
} test_buffer_delayed_refined_model__the_proc_the_sender_behaviorIdentifier_enum;
typedef enum e_test_buffer_delayed_refined_model__the_proc_the_receiver_behaviorIdentifier_enum {
	test_buffer_delayed_refined_model__the_proc_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_buffer_delayed_refined_model__the_proc_the_receiver_behaviorIdentifier_enum_p_in
} test_buffer_delayed_refined_model__the_proc_the_receiver_behaviorIdentifier_enum;
typedef enum e_PeriodicDelayed_runtime__ReturnCodeType {
	PeriodicDelayed_runtime__ReturnCodeType_Ok,
	PeriodicDelayed_runtime__ReturnCodeType_EmptyQueue,
	PeriodicDelayed_runtime__ReturnCodeType_FullQueue
} PeriodicDelayed_runtime__ReturnCodeType;
typedef Base_Types__Integer_16 PeriodicDelayed_runtime__ArrayDataType[];

#endif

