#include "routing.h"
#include "middleware/port.h"
#include <types.h>
uint8_t S1_inst_partport[6] = {S1_inst_Mon_mode_C2,S1_inst_C1_PingOut,S1_inst_C1_PongOut,S1_inst_C1_PingIn,S1_inst_C1_PongIn,S1_inst_Mon_error_C2,};
uint8_t S1_inst_Mon_mode_C2_deployment_destinations[3] = {S2_inst_C2_mode_C2_mode_global,S2_inst_C2_mode_C2_mode_global,S2_inst_C2_mode_C2_mode_global,};
uint8_t S1_inst_C1_PingOut_deployment_destinations[1] = {S2_inst_C2_PingIn_C2_PingIn_global,};
uint8_t S1_inst_C1_PongOut_deployment_destinations[1] = {S2_inst_C2_PongIn_C2_PongIn_global,};
uint8_t S2_inst_partport[6] = {S2_inst_C2_mode,S2_inst_C2_PingIn,S2_inst_C2_PongIn,S2_inst_C2_PingOut,S2_inst_C2_PongOut,S2_inst_C2_badSequenceNumber,};
uint8_t S2_inst_C2_PingOut_deployment_destinations[1] = {S1_inst_C1_PingIn_C1_PingIn_global,};
uint8_t S2_inst_C2_PongOut_deployment_destinations[1] = {S1_inst_C1_PongIn_C1_PongIn_global,};
uint8_t S2_inst_C2_badSequenceNumber_deployment_destinations[1] = {S1_inst_Mon_error_C2_Mon_error_C2_global,};
uint8_t pok_global_ports_to_local_ports[POK_CONFIG_NB_GLOBAL_PORTS] = {S1_inst_Mon_mode_C2,S1_inst_C1_PingOut,S1_inst_C1_PongOut,S1_inst_C1_PingIn,S1_inst_C1_PongIn,S1_inst_Mon_error_C2,S2_inst_C2_mode,S2_inst_C2_PingIn,S2_inst_C2_PongIn,S2_inst_C2_PingOut,S2_inst_C2_PongOut,S2_inst_C2_badSequenceNumber,};
uint8_t pok_global_ports_to_bus[POK_CONFIG_NB_GLOBAL_PORTS] = {invalid_bus,invalid_bus,invalid_bus,invalid_bus,invalid_bus,invalid_bus,invalid_bus,invalid_bus,invalid_bus,invalid_bus,invalid_bus,invalid_bus,};
uint8_t pok_local_ports_to_global_ports[POK_CONFIG_NB_PORTS] = {S1_inst_Mon_mode_C2_Mon_mode_C2_global,S1_inst_C1_PingOut_C1_PingOut_global,S1_inst_C1_PongOut_C1_PongOut_global,S1_inst_C1_PingIn_C1_PingIn_global,S1_inst_C1_PongIn_C1_PongIn_global,S1_inst_Mon_error_C2_Mon_error_C2_global,S2_inst_C2_mode_C2_mode_global,S2_inst_C2_PingIn_C2_PingIn_global,S2_inst_C2_PongIn_C2_PongIn_global,S2_inst_C2_PingOut_C2_PingOut_global,S2_inst_C2_PongOut_C2_PongOut_global,S2_inst_C2_badSequenceNumber_C2_badSequenceNumber_global,};
uint8_t pok_ports_nodes[POK_CONFIG_NB_GLOBAL_PORTS] = {root_inst,root_inst,root_inst,root_inst,root_inst,root_inst,root_inst,root_inst,root_inst,root_inst,root_inst,root_inst,};
uint8_t pok_ports_nb_ports_by_partition[POK_CONFIG_NB_PARTITIONS] = {6,6,};
uint8_t* pok_ports_by_partition[POK_CONFIG_NB_PARTITIONS] = {S1_inst_partport,S2_inst_partport,};
char* pok_ports_names[POK_CONFIG_NB_PORTS] = {"S1_inst_Mon_mode_C2","S1_inst_C1_PingOut","S1_inst_C1_PongOut","S1_inst_C1_PingIn","S1_inst_C1_PongIn","S1_inst_Mon_error_C2","S2_inst_C2_mode","S2_inst_C2_PingIn","S2_inst_C2_PongIn","S2_inst_C2_PingOut","S2_inst_C2_PongOut","S2_inst_C2_badSequenceNumber",};
uint8_t pok_ports_identifiers[POK_CONFIG_NB_PORTS] = {S1_inst_Mon_mode_C2,S1_inst_C1_PingOut,S1_inst_C1_PongOut,S1_inst_C1_PingIn,S1_inst_C1_PongIn,S1_inst_Mon_error_C2,S2_inst_C2_mode,S2_inst_C2_PingIn,S2_inst_C2_PongIn,S2_inst_C2_PingOut,S2_inst_C2_PongOut,S2_inst_C2_badSequenceNumber,};
uint8_t pok_ports_nb_destinations[POK_CONFIG_NB_PORTS] = {3,1,1,0,0,0,0,0,0,1,1,1,};
uint8_t* pok_ports_destinations[POK_CONFIG_NB_PORTS] = {S1_inst_Mon_mode_C2_deployment_destinations,S1_inst_C1_PingOut_deployment_destinations,S1_inst_C1_PongOut_deployment_destinations,NULL,NULL,NULL,NULL,NULL,NULL,S2_inst_C2_PingOut_deployment_destinations,S2_inst_C2_PongOut_deployment_destinations,S2_inst_C2_badSequenceNumber_deployment_destinations,};
uint8_t pok_ports_kind[POK_CONFIG_NB_PORTS] = {POK_PORT_KIND_SAMPLING,POK_PORT_KIND_SAMPLING,POK_PORT_KIND_SAMPLING,POK_PORT_KIND_SAMPLING,POK_PORT_KIND_SAMPLING,POK_PORT_KIND_SAMPLING,POK_PORT_KIND_SAMPLING,POK_PORT_KIND_SAMPLING,POK_PORT_KIND_SAMPLING,POK_PORT_KIND_SAMPLING,POK_PORT_KIND_SAMPLING,POK_PORT_KIND_SAMPLING,};
