#include "activity.h"
#include "main.h"

extern APEX_INTEGER the_cpu1_system_part_comProcess_the_proc1_p_outglobalVariable;
void* test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_impl_Job()
{
  pok_port_id_t test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_impl_the_proc1_p_out_createVirtualPortId;
  Base_Types__String test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_impl_the_proc1_p_out_createVirtualPortName = "the_proc1_p_out_virtual_port";
  pok_port_virtual_create (test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_impl_the_proc1_p_out_createVirtualPortName, &test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_impl_the_proc1_p_out_createVirtualPortId);
  Base_Types__Unsigned_32 test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_impl_the_proc1_p_out_length = sizeof(common_pkg__Integer);
  test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl (&test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_impl_the_proc1_p_out_length, &test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_impl_the_proc1_p_out_createVirtualPortId, &the_cpu1_system_part_comProcess_the_proc1_p_outglobalVariable);
  return 0;
}
void* test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_impl_Job()
{
  rtl8029_init ();
  test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl ();
  return 0;
}
