#ifndef __GENERATED_GTYPES_H__
#define __GENERATED_GTYPES_H__
#include "types.h"
#include "arinc653/queueing.h"
#include "arinc653/types.h"
typedef pok_port_id_t rtl8029_driver__Pok_Port_Id_T;
typedef char * Base_Types__String;
typedef unsigned int Base_Types__Unsigned_32;
typedef APEX_INTEGER arinc653_runtime__Queuing_Port_Id_Type;
typedef RETURN_CODE_TYPE arinc653_runtime__Return_Code_Type;
typedef  int common_pkg__Integer;
typedef SYSTEM_TIME_TYPE arinc653_runtime__System_Time_Type;
typedef enum e_test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_behaviorIdentifier_enum {
	test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_behaviorIdentifier_enum_default_behavior,
	test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_behaviorIdentifier_enum_p_out
} test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_behaviorIdentifier_enum;
typedef enum e_test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_behaviorIdentifier_enum {
	test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_behaviorIdentifier_enum_default_behavior
} test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_behaviorIdentifier_enum;

#endif

