#include "types.h"
#include "arinc653/queueing.h"
#include "subprograms.h"
test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_BA_State_t the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_init_state;
void test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl(
	Base_Types__Unsigned_32 *  the_proc1_p_out_comConnectionLength_len,
	pok_port_id_t *  the_proc1_p_out_comConnectionPortId_port_id,
	APEX_INTEGER *  p_out)
{
  RETURN_CODE_TYPE test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_the_cpu1_system_part_comProcess_system_part_comm_runtime_call_ret;
  common_pkg__Integer test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_p_out_localVariable;
  RETURN_CODE_TYPE test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_p_out_ErrorCode = 0;
  SYSTEM_TIME_TYPE test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_p_out_TimeOut = 0;
  test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_behaviorIdentifier_enum whichPortActivated = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_current_state)
  {
    case test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_the_cpu1_system_part_comProcess_system_part_comm_runtime_call_ret);
      break;
    }
    case test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: the_cpu1_communicationCallSequence -- Priority 0
    if(whichPortActivated == test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_behaviorIdentifier_enum_default_behavior)
    {
      the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      RECEIVE_QUEUING_MESSAGE ((*p_out), test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_p_out_TimeOut, &test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_p_out_localVariable, the_proc1_p_out_comConnectionLength_len, &test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_p_out_ErrorCode);
      if (test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_p_out_ErrorCode == 0) {
      rtl8029_write (*the_proc1_p_out_comConnectionPortId_port_id, &test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_system_part_comm_entrypoint_impl_p_out_localVariable, *the_proc1_p_out_comConnectionLength_len);
      }
      break;
    }
  }
}
}
test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_BA_State_t the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_BA_entrypoint_init_state;
void test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl()
{
  RETURN_CODE_TYPE test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_runtime_call_ret;
  test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_behaviorIdentifier_enum whichPortActivated = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_current_state)
  {
    case test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_runtime_call_ret);
      break;
    }
    case test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: system_part_pollCallSequence -- Priority 0
    if(whichPortActivated == test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_behaviorIdentifier_enum_default_behavior)
    {
      the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_current_state = test_network_rtl8029_remote_communications_refined_model__the_cpu1_system_part_comProcess_the_cpu1_system_part_comm_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      rtl8029_polling ();
      break;
    }
  }
}
}
