#ifndef __GENERATED_SUBPROGRAMS_H__
#define __GENERATED_SUBPROGRAMS_H__
#include "business-code/PingPong_Protocol_Implementations_IPingOrPong_impl.h"
#include "business-code/PingPong_module.h"
#include "arinc653/sampling.h"
#include "business-code/PingPong_Protocol_Implementations_Monitor_impl.h"
#include "arinc653/blackboard.h"
#include "arinc653/time.h"
#include "arinc653/types.h"
#include "gtypes.h"
#include "main.h"
void PingPong__Monitor_delayed_error_C1(
	Exception *  error_C1,
	Exception *  delayed_error_C1);

void PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl(
	BLACKBOARD_ID_TYPE *  error_C1,
	BLACKBOARD_ID_TYPE *  delayed_error_C2,
	BLACKBOARD_ID_TYPE *  PortCnx1_mode_C1,
	BLACKBOARD_ID_TYPE *  PortCnx2_mode_C1,
	BLACKBOARD_ID_TYPE *  PortCnx3_mode_C1,
	SAMPLING_PORT_ID_TYPE *  PortCnx8_mode_C2,
	TYPE *  State_baKeywords,
	PingPong_refined_model__S1_inst_Monitor_changeState_currentState *  Parent_BA_currentState_Access);

typedef enum {
  PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_entrypoint_init_state,
  PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_entrypoint_wait_dispatch_state,
  PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_entrypoint_exec_state,
  PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_entrypoint_final_state
} PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_State_t;

void PingPong__Monitor_delayed_error_C2(
	Exception *  error_C2,
	Exception *  delayed_error_C2);

void PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl(
	SAMPLING_PORT_ID_TYPE *  error_C2,
	BLACKBOARD_ID_TYPE *  PortCnx11_delayed_error_C2,
	TYPE *  State_baKeywords,
	PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_currentState *  Parent_BA_currentState_Access);

typedef enum {
  PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_entrypoint_init_state,
  PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_entrypoint_wait_dispatch_state,
  PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_entrypoint_exec_state,
  PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_entrypoint_final_state
} PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_State_t;

void PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl(
	BLACKBOARD_ID_TYPE *  delayed_PongIn,
	SAMPLING_PORT_ID_TYPE *  PortCnx9_PingOut,
	BLACKBOARD_ID_TYPE *  PortCnx4_badSequenceNumber,
	BLACKBOARD_ID_TYPE *  mode_aadlKeywords,
	SEQ *  seqNb,
	PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_currentState *  Parent_BA_currentState_Access,
	Base_Types__Integer_16 *  PingOut_freshnessIndicator_access);

typedef enum {
  PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_init_state,
  PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_wait_dispatch_state,
  PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_exec_state,
  PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_final_state
} PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_State_t;

void PingPong__IPingOrPong_Cping_delayed_PongIn(
	PingPongMessage *  PongIn,
	PingPongMessage *  delayed_PongIn);

void PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl(
	SAMPLING_PORT_ID_TYPE *  PongIn,
	BLACKBOARD_ID_TYPE *  PortCnx12_delayed_PongIn,
	BLACKBOARD_ID_TYPE *  mode_aadlKeywords,
	SEQ *  seqNb,
	PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_currentState *  Parent_BA_currentState_Access);

typedef enum {
  PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_init_state,
  PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_wait_dispatch_state,
  PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_exec_state,
  PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_final_state
} PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_State_t;

void PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl(
	SAMPLING_PORT_ID_TYPE *  PingIn,
	SAMPLING_PORT_ID_TYPE *  PortCnx10_PongOut,
	BLACKBOARD_ID_TYPE *  mode_aadlKeywords,
	SEQ *  seqNb,
	PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_currentState *  Parent_BA_currentState_Access,
	Base_Types__Integer_16 *  PingIn_freshnessIndicator_access);

typedef enum {
  PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_init_state,
  PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_wait_dispatch_state,
  PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_exec_state,
  PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_final_state
} PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_State_t;


#endif

