#include "arinc653/sampling.h"
#include "arinc653/blackboard.h"
#include "business-code/PingPong_module.h"
#include "subprograms.h"
void PingPong__Monitor_delayed_error_C1(Exception *  error_C1, Exception *  delayed_error_C1)
{
}
PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_State_t S1_inst_Monitor_changeState_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_entrypoint_init_state;
void PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl(TYPE *  State_baKeywords, BLACKBOARD_ID_TYPE *  error_C1, BLACKBOARD_ID_TYPE *  delayed_error_C2, BLACKBOARD_ID_TYPE *  PortCnx1_mode_C1, BLACKBOARD_ID_TYPE *  PortCnx2_mode_C1, BLACKBOARD_ID_TYPE *  PortCnx3_mode_C1, SAMPLING_PORT_ID_TYPE *  PortCnx8_mode_C2, PingPong_refined_model__S1_inst_Monitor_changeState_currentState *  Parent_BA_currentState_Access)
{
  Exception PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_error_C1_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_error_C1_Length = sizeof(Exception);
  Exception PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_delayed_error_C2_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_delayed_error_C2_Length = sizeof(Exception);
  ROLE PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_mode_C1_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_mode_C1_Length = sizeof(ROLE);
  ROLE PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_mode_C2_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_mode_C2_Length = sizeof(ROLE);
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_error_C1_ErrorCode = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_delayed_error_C2_ErrorCode = 0;
  SYSTEM_TIME_TYPE PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_error_C1_TimeOut = 0;
  SYSTEM_TIME_TYPE PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_delayed_error_C2_TimeOut = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_S1_inst_Monitor_changeState_runtime_call_ret;
  Exception delayed_error_C1;
PingPong_refined_model__S1_inst_Monitor_changeState_behaviorIdentifier_enum whichPortActivated = PingPong_refined_model__S1_inst_Monitor_changeState_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(S1_inst_Monitor_changeState_entrypoint_impl_current_state)
  {
    case PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      S1_inst_Monitor_changeState_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = PingPong_refined_model__S1_inst_Monitor_changeState_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      S1_inst_Monitor_changeState_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_S1_inst_Monitor_changeState_runtime_call_ret);
      break;
    }
    case PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == PingPong_refined_model__S1_inst_Monitor_changeState_behaviorIdentifier_enum_default_behavior)
    {
      S1_inst_Monitor_changeState_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == PingPong_refined_model__S1_inst_Monitor_changeState_currentState_switch) {
      READ_BLACKBOARD ((*error_C1), PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_error_C1_TimeOut, &PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_error_C1_localVariable, &PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_error_C1_Length, &PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_S1_inst_Monitor_changeState_runtime_call_ret);
      READ_BLACKBOARD ((*delayed_error_C2), PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_delayed_error_C2_TimeOut, &PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_delayed_error_C2_localVariable, &PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_delayed_error_C2_Length, &PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_S1_inst_Monitor_changeState_runtime_call_ret);
      PingPong__Monitor_delayed_error_C1 (&PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_error_C1_localVariable, &delayed_error_C1);
      Monitor_changeState (&delayed_error_C1, &PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_delayed_error_C2_localVariable, &PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_mode_C1_localVariable, &PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_mode_C2_localVariable, State_baKeywords, State_baKeywords);
      DISPLAY_BLACKBOARD ((*PortCnx3_mode_C1), &PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_mode_C1_localVariable, PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_mode_C1_Length, &PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_S1_inst_Monitor_changeState_runtime_call_ret);
      PERIODIC_WAIT (&PingPong_refined_model__S1_inst_Monitor_changeState_entrypoint_impl_S1_inst_Monitor_changeState_runtime_call_ret);
      (*Parent_BA_currentState_Access) = PingPong_refined_model__S1_inst_Monitor_changeState_currentState_switch;
      }
      break;
    }
  }
}
}
void PingPong__Monitor_delayed_error_C2(Exception *  error_C2, Exception *  delayed_error_C2)
{
}
PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_State_t S1_inst_Monitor_delayed_error_C2_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_entrypoint_init_state;
void PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl(TYPE *  State_baKeywords, SAMPLING_PORT_ID_TYPE *  error_C2, BLACKBOARD_ID_TYPE *  PortCnx11_delayed_error_C2, PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_currentState *  Parent_BA_currentState_Access)
{
  Exception PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_error_C2_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_error_C2_Length = sizeof(Exception);
  Exception PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_delayed_error_C2_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_delayed_error_C2_Length = sizeof(Exception);
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_error_C2_ErrorCode = 0;
  VALIDITY_TYPE PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_error_C2_Validity;
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_S1_inst_Monitor_delayed_error_C2_runtime_call_ret;
  PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_behaviorIdentifier_enum whichPortActivated = PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(S1_inst_Monitor_delayed_error_C2_entrypoint_impl_current_state)
  {
    case PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      S1_inst_Monitor_delayed_error_C2_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      S1_inst_Monitor_delayed_error_C2_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_S1_inst_Monitor_delayed_error_C2_runtime_call_ret);
      break;
    }
    case PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_behaviorIdentifier_enum_default_behavior)
    {
      S1_inst_Monitor_delayed_error_C2_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_currentState_switch) {
      READ_SAMPLING_MESSAGE ((*error_C2), &PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_error_C2_localVariable, PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_error_C2_Length, &PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_error_C2_Validity, &PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_S1_inst_Monitor_delayed_error_C2_runtime_call_ret);
      PingPong__Monitor_delayed_error_C2 (&PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_error_C2_localVariable, &PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_delayed_error_C2_localVariable);
      DISPLAY_BLACKBOARD ((*PortCnx11_delayed_error_C2), &PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_delayed_error_C2_localVariable, PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_delayed_error_C2_Length, &PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_S1_inst_Monitor_delayed_error_C2_runtime_call_ret);
      PERIODIC_WAIT (&PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_entrypoint_impl_S1_inst_Monitor_delayed_error_C2_runtime_call_ret);
      (*Parent_BA_currentState_Access) = PingPong_refined_model__S1_inst_Monitor_delayed_error_C2_currentState_switch;
      }
      break;
    }
  }
}
}
PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_State_t S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_init_state;
void PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl(SEQ *  seqNb, BLACKBOARD_ID_TYPE *  delayed_PongIn, BLACKBOARD_ID_TYPE *  mode_aadlKeywords, SAMPLING_PORT_ID_TYPE *  PortCnx9_PingOut, BLACKBOARD_ID_TYPE *  PortCnx4_badSequenceNumber, PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_currentState *  Parent_BA_currentState_Access, Base_Types__Integer_16 *  PingOut_freshnessIndicator_access)
{
  PingPongMessage PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_Length = sizeof(PingPongMessage);
  PingPong_refined_model__PingPongMessage_freshness_t_impl PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_PingOut_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_PingOut_Length = sizeof(PingPong_refined_model__PingPongMessage_freshness_t_impl);
  Exception PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_badSequenceNumber_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_badSequenceNumber_Length = sizeof(Exception);
  ROLE PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_Length = sizeof(ROLE);
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_ErrorCode = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_ErrorCode = 0;
  SYSTEM_TIME_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_TimeOut = 0;
  SYSTEM_TIME_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_TimeOut = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_S1_inst_IPingOrPong_Cping_ping_runtime_call_ret;
  PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_behaviorIdentifier_enum whichPortActivated = PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_current_state)
  {
    case PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_S1_inst_IPingOrPong_Cping_ping_runtime_call_ret);
      break;
    }
    case PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_behaviorIdentifier_enum_default_behavior)
    {
      S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_currentState_switch) {
      READ_BLACKBOARD ((*delayed_PongIn), PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_TimeOut, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_localVariable, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_Length, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_S1_inst_IPingOrPong_Cping_ping_runtime_call_ret);
      READ_BLACKBOARD ((*mode_aadlKeywords), PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_TimeOut, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_localVariable, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_Length, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_S1_inst_IPingOrPong_Cping_ping_runtime_call_ret);
      if (PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_mode_aadlKeywords_localVariable == E_ROLE_CPING) {
      IPingOrPong_Cping_ping (&PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_delayed_PongIn_localVariable, &(PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_PingOut_localVariable.pvalue), &PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_badSequenceNumber_localVariable, seqNb, seqNb);
      }
      (*PingOut_freshnessIndicator_access) = (*PingOut_freshnessIndicator_access) + 1;
      PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_PingOut_localVariable.fresh_ba = (*PingOut_freshnessIndicator_access);
      DISPLAY_BLACKBOARD ((*PortCnx4_badSequenceNumber), &PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_badSequenceNumber_localVariable, PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_badSequenceNumber_Length, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_S1_inst_IPingOrPong_Cping_ping_runtime_call_ret);
      PERIODIC_WAIT (&PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_entrypoint_impl_S1_inst_IPingOrPong_Cping_ping_runtime_call_ret);
      (*Parent_BA_currentState_Access) = PingPong_refined_model__S1_inst_IPingOrPong_Cping_ping_currentState_switch;
      }
      break;
    }
  }
}
}
void PingPong__IPingOrPong_Cping_delayed_PongIn(PingPongMessage *  PongIn, PingPongMessage *  delayed_PongIn)
{
}
PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_State_t S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_init_state;
void PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl(SEQ *  seqNb, SAMPLING_PORT_ID_TYPE *  PongIn, BLACKBOARD_ID_TYPE *  mode_aadlKeywords, BLACKBOARD_ID_TYPE *  PortCnx12_delayed_PongIn, PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_currentState *  Parent_BA_currentState_Access)
{
  PingPongMessage PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_Length = sizeof(PingPongMessage);
  PingPongMessage PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_delayed_PongIn_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_delayed_PongIn_Length = sizeof(PingPongMessage);
  ROLE PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_Length = sizeof(ROLE);
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_ErrorCode = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_ErrorCode = 0;
  VALIDITY_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_Validity;
  SYSTEM_TIME_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_TimeOut = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S1_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret;
  PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_behaviorIdentifier_enum whichPortActivated = PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_current_state)
  {
    case PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S1_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret);
      break;
    }
    case PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_behaviorIdentifier_enum_default_behavior)
    {
      S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_currentState_switch) {
      READ_SAMPLING_MESSAGE ((*PongIn), &PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_localVariable, PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_Length, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_Validity, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S1_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret);
      READ_BLACKBOARD ((*mode_aadlKeywords), PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_TimeOut, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_localVariable, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_Length, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S1_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret);
      if (PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_mode_aadlKeywords_localVariable == E_ROLE_CPING) {
      PingPong__IPingOrPong_Cping_delayed_PongIn (&PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_PongIn_localVariable, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_delayed_PongIn_localVariable);
      }
      DISPLAY_BLACKBOARD ((*PortCnx12_delayed_PongIn), &PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_delayed_PongIn_localVariable, PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_delayed_PongIn_Length, &PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S1_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret);
      PERIODIC_WAIT (&PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_entrypoint_impl_S1_inst_IPingOrPong_Cping_delayed_PongIn_runtime_call_ret);
      (*Parent_BA_currentState_Access) = PingPong_refined_model__S1_inst_IPingOrPong_Cping_delayed_PongIn_currentState_switch;
      }
      break;
    }
  }
}
}
PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_State_t S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_init_state;
void PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl(SEQ *  seqNb, SAMPLING_PORT_ID_TYPE *  PingIn, BLACKBOARD_ID_TYPE *  mode_aadlKeywords, SAMPLING_PORT_ID_TYPE *  PortCnx10_PongOut, PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_currentState *  Parent_BA_currentState_Access, Base_Types__Integer_16 *  PingIn_freshnessIndicator_access)
{
  PingPong_refined_model__PingPongMessage_freshness_t_impl PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_Length = sizeof(PingPong_refined_model__PingPongMessage_freshness_t_impl);
  PingPongMessage PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PongOut_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PongOut_Length = sizeof(PingPongMessage);
  ROLE PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_Length = sizeof(ROLE);
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_ErrorCode = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_ErrorCode = 0;
  VALIDITY_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_Validity;
  SYSTEM_TIME_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_TimeOut = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_S1_inst_IPingOrPong_Cpong_pong_runtime_call_ret;
  PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_behaviorIdentifier_enum whichPortActivated = PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_current_state)
  {
    case PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_S1_inst_IPingOrPong_Cpong_pong_runtime_call_ret);
      break;
    }
    case PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: behavior_specification_1 -- Priority 0
    if(whichPortActivated == PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_behaviorIdentifier_enum_default_behavior)
    {
      S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      if ((*Parent_BA_currentState_Access) == PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_currentState_switch) {
      READ_SAMPLING_MESSAGE ((*PingIn), &PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_localVariable, PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_Length, &PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_Validity, &PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_S1_inst_IPingOrPong_Cpong_pong_runtime_call_ret);
      READ_BLACKBOARD ((*mode_aadlKeywords), PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_TimeOut, &PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_localVariable, &PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_Length, &PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_S1_inst_IPingOrPong_Cpong_pong_runtime_call_ret);
      if (PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_mode_aadlKeywords_localVariable == E_ROLE_CPONG) {
      if ((PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_localVariable.fresh_ba != (*PingIn_freshnessIndicator_access))) {
      IPingOrPong_Cpong_pong (&PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_localVariable.pvalue, &PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PongOut_localVariable);
      }
      }
      (*PingIn_freshnessIndicator_access) = PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_PingIn_localVariable.fresh_ba;
      PERIODIC_WAIT (&PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_entrypoint_impl_S1_inst_IPingOrPong_Cpong_pong_runtime_call_ret);
      (*Parent_BA_currentState_Access) = PingPong_refined_model__S1_inst_IPingOrPong_Cpong_pong_currentState_switch;
      }
      break;
    }
  }
}
}
