<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graph" nsURI="http://fr.tpt.aadl.ramses.transformation/DependencyGraph/1.0"
    nsPrefix="fr.tpt.aadl.ramses.transformation.selection.dependency">
  <eClassifiers xsi:type="ecore:EClass" name="DependencyGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//DependencyNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outArcs" upperBound="-1"
        eType="#//DependencyArc" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inArcs" upperBound="-1"
        eType="#//DependencyArc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchedElements" lowerBound="1"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationRule" eType="ecore:EClass ../../fr.tpt.aadl.ramses.transformation.trc/model/TRC.ecore#//TrcRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyArc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceNode" lowerBound="1"
        eType="#//DependencyNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetNode" lowerBound="1"
        eType="#//DependencyNode"/>
  </eClassifiers>
</ecore:EPackage>
