/*
 * generated by Xtext
 */
package fr.tpt.aadl.ramses.transformation.trc.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTRCValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(fr.tpt.aadl.ramses.transformation.trc.xtext.tRC.TRCPackage.eINSTANCE);
		return result;
	}
}
