/*
 * generated by Xtext
 */
package fr.tpt.aadl.ramses.transformation.trc.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TRCUiModule extends fr.tpt.aadl.ramses.transformation.trc.xtext.ui.AbstractTRCUiModule {
	public TRCUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
