#ifndef __GENERATED_DEPLOYMENT_H__
#define __GENERATED_DEPLOYMENT_H__

#include "routing.h"
#define POK_NEEDS_CONSOLE 1
#define POK_CONFIG_LOCAL_NODE 0
#define POK_GENERATED_CODE 1
#define POK_NEEDS_GETTICK 1
#define POK_NEEDS_THREADS 1
#define POK_NEEDS_PARTITIONS 1
#define POK_NEEDS_DEBUG 1
#define POK_NEEDS_SCHED 1
#define POK_CONFIG_NB_PARTITIONS 1
#define POK_CONFIG_NB_THREADS 5
#define POK_CONFIG_PARTITIONS_NTHREADS {3}
#define POK_NEEDS_SCHED_RMS 1
#define POK_CONFIG_PARTITIONS_SCHEDULER {POK_SCHED_RMS}
#define POK_NEEDS_LOCKOBJECTS 1
#define POK_CONFIG_PARTITIONS_NLOCKOBJECTS {1}
#define POK_CONFIG_PARTITIONS_SIZE {200000}
#define POK_CONFIG_SCHEDULING_NBSLOTS 1
#define POK_CONFIG_SCHEDULING_SLOTS {1000}
#define POK_CONFIG_SCHEDULING_SLOTS_ALLOCATION {0}
#define POK_CONFIG_SCHEDULING_MAJOR_FRAME 1000
#define POK_CONFIG_STACKS_SIZE 80000
#define POK_CONFIG_NB_BUSES 0
#define POK_NEEDS_ERROR_HANDLING 1
#define POK_USE_GENERATED_KERNEL_ERROR_HANDLER 1
#define POK_USE_GENERATED_PARTITION_ERROR_HANDLER 1
#include "core/partition.h"
#include "core/error.h"
#include "core/kernel.h"
#endif
