/**
 * generated by Xtext
 */
package fr.tpt.aadl.ramses.transformation.trc.xtext.validation;

import fr.tpt.aadl.ramses.transformation.trc.xtext.validation.AbstractTRCValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TRCValidator extends AbstractTRCValidator {
}
