/*
* generated by Xtext
*/
package fr.tpt.aadl.ramses.transformation.trc.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TRCUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.tpt.aadl.ramses.transformation.trc.xtext.ui.internal.TRCActivator.getInstance().getInjector("fr.tpt.aadl.ramses.transformation.trc.xtext.TRC");
	}
	
}
