#include "deployment.h"
SAMPLING_PORT_ID_TYPE S1_inst_C1_PingInglobalVariable;
SAMPLING_PORT_ID_TYPE S1_inst_C1_PongOut_globalVariable;
SAMPLING_PORT_ID_TYPE S1_inst_C1_PingOut_globalVariable;
SAMPLING_PORT_ID_TYPE S1_inst_Mon_mode_C2_globalVariable;
SAMPLING_PORT_ID_TYPE S1_inst_Mon_error_C2globalVariable;
SAMPLING_PORT_ID_TYPE S1_inst_C1_PongInglobalVariable;
TYPE state_baKeywords;
