#include "arinc653/sampling.h"
#include "pingpong.h"
#include "subprograms.h"
PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_BA_State_t S1_inst_a1_inst_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_BA_entrypoint_init_state;
void PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl(SAMPLING_PORT_ID_TYPE *  C1_PingIn, SAMPLING_PORT_ID_TYPE *  C1_PongIn, SAMPLING_PORT_ID_TYPE *  Mon_error_C2, SAMPLING_PORT_ID_TYPE *  mode_implicit_cnx_Mon_mode_C2, SAMPLING_PORT_ID_TYPE *  C1_ping_implicit_cnx_C1_PingOut, SAMPLING_PORT_ID_TYPE *  C1_pong_implicit_cnx_C1_PongOut, TYPE *  call_seq_state_baKeywords_entrypoint, SEQ *  call_seq_seqNb_entrypoint)
{
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_S1_inst_a1_inst_runtime_call_ret;
  ROLE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_mode_C2_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_mode_C2_Length = sizeof(ROLE);
  PingPongMessage PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingOut_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingOut_Length = sizeof(PingPongMessage);
  PingPongMessage PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongOut_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongOut_Length = sizeof(PingPongMessage);
  PingPongMessage PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingIn_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingIn_Length = sizeof(PingPongMessage);
  PingPongMessage PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongIn_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongIn_Length = sizeof(PingPongMessage);
  PingPong__Exception PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_error_C2_localVariable;
  MESSAGE_SIZE_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_error_C2_Length = sizeof(PingPong__Exception);
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingIn_ErrorCode = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongIn_ErrorCode = 0;
  RETURN_CODE_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_error_C2_ErrorCode = 0;
  VALIDITY_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingIn_Validity;
  VALIDITY_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongIn_Validity;
  VALIDITY_TYPE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_error_C2_Validity;
  PingPong__Exception PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_PingPong_IPingOrPong_mode_badSequenceNumber_localVariable;
  ROLE PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_PingPong_Monitor_activate_mode_C1_localVariable;
  PingPong_refined_model__S1_inst_a1_inst_behaviorIdentifier_enum whichPortActivated = PingPong_refined_model__S1_inst_a1_inst_behaviorIdentifier_enum_default_behavior;
while(1)
{
  switch(S1_inst_a1_inst_entrypoint_impl_current_state)
  {
    case PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_BA_entrypoint_init_state:
    // Transition id: which_behavior_default_mode
    if(1) // no execution condition
    {
      S1_inst_a1_inst_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_BA_entrypoint_exec_state;
      whichPortActivated = PingPong_refined_model__S1_inst_a1_inst_behaviorIdentifier_enum_default_behavior;
      break;
    }
    case PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_BA_entrypoint_wait_dispatch_state:
    // Transition id: dispatch_transition
    if(1) // no execution condition
    {
      S1_inst_a1_inst_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_BA_entrypoint_exec_state;
      PERIODIC_WAIT (&PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_S1_inst_a1_inst_runtime_call_ret);
      break;
    }
    case PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_BA_entrypoint_exec_state:
    // Transition id: call_seq -- Priority 0
    if(whichPortActivated == PingPong_refined_model__S1_inst_a1_inst_behaviorIdentifier_enum_default_behavior)
    {
      S1_inst_a1_inst_entrypoint_impl_current_state = PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_BA_entrypoint_wait_dispatch_state;
      READ_SAMPLING_MESSAGE ((*C1_PingIn), &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingIn_localVariable, PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingIn_Length, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingIn_Validity, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingIn_ErrorCode);
      READ_SAMPLING_MESSAGE ((*C1_PongIn), &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongIn_localVariable, PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongIn_Length, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongIn_Validity, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongIn_ErrorCode);
      READ_SAMPLING_MESSAGE ((*Mon_error_C2), &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_error_C2_localVariable, PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_error_C2_Length, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_error_C2_Validity, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_error_C2_ErrorCode);
      if (PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_error_C2_ErrorCode == 0) {
      activate (call_seq_state_baKeywords_entrypoint, PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_PingPong_IPingOrPong_mode_badSequenceNumber_localVariable, PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_error_C2_localVariable, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_PingPong_Monitor_activate_mode_C1_localVariable, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_mode_C2_localVariable);
      }
      if (PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingIn_ErrorCode == 0 && PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongIn_ErrorCode == 0) {
      mode (call_seq_seqNb_entrypoint, PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingIn_localVariable, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingOut_localVariable, PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongIn_localVariable, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongOut_localVariable, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_PingPong_IPingOrPong_mode_badSequenceNumber_localVariable, PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_PingPong_Monitor_activate_mode_C1_localVariable);
      }
      WRITE_SAMPLING_MESSAGE ((*mode_implicit_cnx_Mon_mode_C2), &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_mode_C2_localVariable, PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_Mon_mode_C2_Length, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_S1_inst_a1_inst_runtime_call_ret);
      WRITE_SAMPLING_MESSAGE ((*C1_ping_implicit_cnx_C1_PingOut), &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingOut_localVariable, PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PingOut_Length, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_S1_inst_a1_inst_runtime_call_ret);
      WRITE_SAMPLING_MESSAGE ((*C1_pong_implicit_cnx_C1_PongOut), &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongOut_localVariable, PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_C1_PongOut_Length, &PingPong_refined_model__S1_inst_a1_inst_entrypoint_impl_S1_inst_a1_inst_runtime_call_ret);
      break;
    }
  }
}
}
