/*
 * generated by Xtext
 */
package org.trc.xtext.dsl.ui.contentassist

import org.trc.xtext.dsl.ui.contentassist.AbstractDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DslProposalProvider extends AbstractDslProposalProvider {
}
