/*
* generated by Xtext
*/
package org.trc.xtext.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.trc.xtext.dsl.ui.internal.DslActivator.getInstance().getInjector("org.trc.xtext.dsl.Dsl");
	}
	
}
