#ifndef __GENERATED_DEPLOYMENT_H_
#define __GENERATED_DEPLOYMENT_H_


#include "routing.h"
#define POK_NEEDS_CONSOLE 1
#define POK_CONFIG_LOCAL_NODE 0
#define POK_GENERATED_CODE 1
#define POK_NEEDS_GETTICK 1
#define POK_NEEDS_THREADS 1
#define POK_NEEDS_PARTITIONS 1
#define POK_NEEDS_DEBUG 1
#define POK_NEEDS_SCHED 1
#define POK_CONFIG_NB_PARTITIONS 1
#define POK_CONFIG_NB_THREADS 5
#define POK_CONFIG_PARTITIONS_NTHREADS {3}
#define POK_NEEDS_SCHED_RR 1
#define POK_CONFIG_PARTITIONS_SCHEDULER {POK_SCHED_RR}
#define POK_CONFIG_PARTITIONS_NLOCKOBJECTS {0}
#define POK_CONFIG_PARTITIONS_SIZE {80000}
#define POK_CONFIG_SCHEDULING_SLOTS {1000}
#define POK_CONFIG_SCHEDULING_NBSLOTS 1
#define POK_CONFIG_SCHEDULING_SLOTS_ALLOCATION {0}
#define POK_CONFIG_SCHEDULING_MAJOR_FRAME 1000
#define POK_CONFIG_STACKS_SIZE 80000
#define POK_CONFIG_NB_BUSES 0
#endif
