#ifndef __GENERATED_GTYPES_H__
#define __GENERATED_GTYPES_H__
#include "arinc653/sampling.h"
#include "arinc653/types.h"
typedef enum e_test_sampling_refined_model__the_proc1_the_sender_behaviorIdentifier_enum {
	test_sampling_refined_model__the_proc1_the_sender_behaviorIdentifier_enum_default_behavior
} test_sampling_refined_model__the_proc1_the_sender_behaviorIdentifier_enum;
typedef SAMPLING_PORT_ID_TYPE arinc653_runtime__Sampling_Port_Id_Type;
typedef RETURN_CODE_TYPE arinc653_runtime__Return_Code_Type;
typedef  int common_pkg__Integer;
typedef MESSAGE_SIZE_TYPE arinc653_runtime__Message_Size_Type;
typedef VALIDITY_TYPE arinc653_runtime__Validity_Type;
typedef enum e_test_sampling_refined_model__the_proc2_the_receiver_behaviorIdentifier_enum {
	test_sampling_refined_model__the_proc2_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_sampling_refined_model__the_proc2_the_receiver_behaviorIdentifier_enum_p_in
} test_sampling_refined_model__the_proc2_the_receiver_behaviorIdentifier_enum;

#endif

