#ifndef __GENERATED_GTYPES_H__
#define __GENERATED_GTYPES_H__
#include "arinc653/types.h"
#include "arinc653/event.h"
#include "arinc653/buffer.h"
typedef BUFFER_ID_TYPE BUFFER_ID_TYPE;
typedef EVENT_ID_TYPE EVENT_ID_TYPE;
typedef RETURN_CODE_TYPE RETURN_CODE_TYPE;
typedef  int common_pkg__Integer;
typedef MESSAGE_SIZE_TYPE MESSAGE_SIZE_TYPE;
typedef SYSTEM_TIME_TYPE SYSTEM_TIME_TYPE;
typedef enum e_test_sporadic_refined_model__the_proc_the_sender_behaviorIdentifier_enum {
	test_sporadic_refined_model__the_proc_the_sender_behaviorIdentifier_enum_default_behavior
} test_sporadic_refined_model__the_proc_the_sender_behaviorIdentifier_enum;
typedef enum e_test_sporadic_refined_model__the_proc_the_receiver_behaviorIdentifier_enum {
	test_sporadic_refined_model__the_proc_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_sporadic_refined_model__the_proc_the_receiver_behaviorIdentifier_enum_p_in
} test_sporadic_refined_model__the_proc_the_receiver_behaviorIdentifier_enum;
typedef enum e_test_sporadic_refined_model__the_proc_the_periodic_behaviorIdentifier_enum {
	test_sporadic_refined_model__the_proc_the_periodic_behaviorIdentifier_enum_default_behavior
} test_sporadic_refined_model__the_proc_the_periodic_behaviorIdentifier_enum;

#endif

