<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hooks"
    nsURI="http://fr.tpt.aadl.ramses.transformation.atl.launch" nsPrefix="hooks">
  <eClassifiers xsi:type="ecore:EClass" name="HookAccess">
    <eOperations name="createBehaviorAnnex" lowerBound="1" eType="ecore:EClass ../../fr.tpt.aadl.annex.behavior/model/aadlba.ecore#//BehaviorAnnex">
      <eParameters name="threadImpl" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//ThreadImplementation"/>
    </eOperations>
    <eOperations name="setDirectionIn">
      <eParameters name="feature" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//DirectedFeature"/>
    </eOperations>
    <eOperations name="resolveBANames">
      <eParameters name="ba" lowerBound="1" eType="ecore:EClass ../../fr.tpt.aadl.annex.behavior/model/aadlba.ecore#//BehaviorAnnex"/>
    </eOperations>
    <eOperations name="orderFeatures" upperBound="-1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//Feature">
      <eParameters name="cpt" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//ComponentType"/>
    </eOperations>
    <eOperations name="copyLocationReference">
      <eParameters name="target" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//Element"/>
      <eParameters name="source" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//Element"/>
    </eOperations>
    <eOperations name="addTransformationBackTrace" lowerBound="1">
      <eParameters name="targetDeclarative" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/aadl2.ecore#//NamedElement"/>
      <eParameters name="sourceInstance" lowerBound="1" eType="ecore:EClass ../../org.osate.aadl2/model/instance.ecore#//InstanceObject"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
