#include "deployment.h"
SAMPLING_PORT_ID_TYPE S2_inst_C2_badSequenceNumber_globalVariable;
SAMPLING_PORT_ID_TYPE S2_inst_C2_PingOut_globalVariable;
SAMPLING_PORT_ID_TYPE S2_inst_C2_PongInglobalVariable;
SAMPLING_PORT_ID_TYPE S2_inst_C2_modeglobalVariable;
SAMPLING_PORT_ID_TYPE S2_inst_C2_PingInglobalVariable;
SAMPLING_PORT_ID_TYPE S2_inst_C2_PongOut_globalVariable;
