#ifndef __GENERATED_GTYPES_H__
#define __GENERATED_GTYPES_H__
#include "kernel.h"
typedef enum e_nxtTypes__nxt_motor_port {
	nxtTypes__nxt_motor_port_NXT_PORT_A,
	nxtTypes__nxt_motor_port_NXT_PORT_B,
	nxtTypes__nxt_motor_port_NXT_PORT_C
} nxtTypes__nxt_motor_port;
typedef  int motorTypes__brake;
typedef  int motorTypes__speed;
typedef StatusType OSEK_runtime__StatusType;
typedef enum e_test_osek_dataports_refined_model__the_proc_the_sender_behaviorIdentifier_enum {
	test_osek_dataports_refined_model__the_proc_the_sender_behaviorIdentifier_enum_default_behavior
} test_osek_dataports_refined_model__the_proc_the_sender_behaviorIdentifier_enum;
typedef enum e_test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum {
	test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum_p
} test_osek_dataports_refined_model__the_proc_the_receiver_behaviorIdentifier_enum;
typedef enum e_test_osek_eventdataports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum {
	test_osek_eventdataports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum_default_behavior
} test_osek_eventdataports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum;
typedef enum e_test_osek_eventdataports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum {
	test_osek_eventdataports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_osek_eventdataports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum_p
} test_osek_eventdataports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum;
typedef enum e_test_osek_eventports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum {
	test_osek_eventports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum_default_behavior
} test_osek_eventports_refined_model__the_proc1_the_sender_behaviorIdentifier_enum;
typedef enum e_test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum {
	test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum_p
} test_osek_eventports_refined_model__the_proc1_the_receiver_behaviorIdentifier_enum;
typedef enum e_motorTest_refined_model__proces_th_behaviorIdentifier_enum {
	motorTest_refined_model__proces_th_behaviorIdentifier_enum_default_behavior
} motorTest_refined_model__proces_th_behaviorIdentifier_enum;

#endif

