TARGET = proces_OSEK
TOPPERS_OSEK_OIL_SOURCE = ./proces.oil
TARGET_SOURCES = main.c activity.c subprograms.c gtypes.c deployment.c 
export USER_INCLUDES=/opt/sandbox/nxtOSEK-ramses /opt/repositories/patterns-transformations/motorTest/input /opt/repositories/patterns-transformations/motorTest/input/instances /opt/repositories/patterns-transformations/motorTest /home/castella/tools/ramses-install-test/../../../../opt/repositories/ramses-develop/model2model/fr.tpt.aadl.ramses.transformation.atl/aadl_resources/C_runtime/PeriodicDelayed_runtime /home/castella/tools/ramses-install-test/../../../../opt/repositories/ramses-develop/model2model/fr.tpt.aadl.ramses.transformation.atl/aadl_resources/C_runtime/OSEK 
O_PATH ?= build
include /opt/sandbox/nxtOSEK-ramses/ecrobot/ecrobot.mak
