#include "deployment.h"
BLACKBOARD_ID_TYPE TrainSimu_trainSimulation_delayed_trainDataIn_globalVariable;
SAMPLING_PORT_ID_TYPE railway_inst_EoaSending_inst_eoaForVobcOut_globalVariable;
BLACKBOARD_ID_TYPE ViuTrainPositionEstimation_viuTrainPositionEstimation_trackIn_globalVariable;
SAMPLING_PORT_ID_TYPE railway_inst_TrainSimu_inst_trainDataOut_globalVariable;
SAMPLING_PORT_ID_TYPE railway_inst_TrainSimu_inst_trainDataInglobalVariable;
BLACKBOARD_ID_TYPE TrainPositionsCorrelation_trainPositionsCorrelation_trainPositionViuForMauIn_globalVariable;
SAMPLING_PORT_ID_TYPE railway_inst_TrainPositionsCorrelation_inst_trainPositionVobcForMauInglobalVariable;
