#include "deployment.h"
cbtc_refined_model__railway_inst_TrainSimu_delayed_trainDataIn_currentState TrainSimu_delayed_trainDataInParent_BA_currentState = cbtc_refined_model__railway_inst_TrainSimu_delayed_trainDataIn_currentState_switch;
SAMPLING_PORT_ID_TYPE railway_inst_TrainSimu_inst_trainDataOut_globalVariable;
BLACKBOARD_ID_TYPE TrainPositionsCorrelation_trainPositionsCorrelation_trainPositionViuForMauIn_globalVariable;
SAMPLING_PORT_ID_TYPE railway_inst_EoaSending_inst_eoaForVobcOut_globalVariable;
SAMPLING_PORT_ID_TYPE railway_inst_TrainSimu_inst_trainDataInglobalVariable;
cbtc_refined_model__railway_inst_ViuTrainPositionEstimation_viuTrainPositionEstimation_currentState ViuTrainPositionEstimation_viuTrainPositionEstimationParent_BA_currentState = cbtc_refined_model__railway_inst_ViuTrainPositionEstimation_viuTrainPositionEstimation_currentState_switch;
SAMPLING_PORT_ID_TYPE railway_inst_TrainPositionsCorrelation_inst_trainPositionVobcForMauInglobalVariable;
cbtc_refined_model__railway_inst_TrainPositionsCorrelation_trainPositionsCorrelation_currentState TrainPositionsCorrelation_trainPositionsCorrelationParent_BA_currentState = cbtc_refined_model__railway_inst_TrainPositionsCorrelation_trainPositionsCorrelation_currentState_switch;
BLACKBOARD_ID_TYPE TrainSimu_trainSimulation_delayed_trainDataIn_globalVariable;
BLACKBOARD_ID_TYPE ViuTrainPositionEstimation_viuTrainPositionEstimation_trackIn_globalVariable;
cbtc_refined_model__railway_inst_TrainSimu_trainSimulation_currentState TrainSimu_trainSimulationParent_BA_currentState = cbtc_refined_model__railway_inst_TrainSimu_trainSimulation_currentState_switch;
