echo Executing NeXTTool to upload /home/castella/sandbox/nxtOSEK-ramses/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
wineconsole /cygdrive/C/cygwin/nexttool/NeXTTool.exe /COM=usb -firmware=/home/castella/sandbox/nxtOSEK-ramses/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
