#ifndef __GENERATED_GTYPES_H__
#define __GENERATED_GTYPES_H__
#include "osek_runtime.h"
#include "kernel.h"
typedef thread_queue_t OSEK_runtime__ThreadQueueType;
typedef StatusType OSEK_runtime__StatusType;
typedef signed int Base_Types__Integer_16;
typedef unsigned int Base_Types__Unsigned_8;
typedef struct __sender_spg_context {
	Base_Types__Unsigned_8 result;
} __sender_spg_context;
typedef enum e_test_osek_modes_modes_refined_refined_model__the_proc_modes_the_sender_behaviorIdentifier_enum {
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_sender_behaviorIdentifier_enum_default_behavior
} test_osek_modes_modes_refined_refined_model__the_proc_modes_the_sender_behaviorIdentifier_enum;
typedef data_port_t OSEK_runtime__DataPortType;
typedef  int test_osek_modes__Integer;
typedef enum e_test_osek_modes_modes_refined__the_proc_modes_modeDataClassifier {
	test_osek_modes_modes_refined__the_proc_modes_modeDataClassifier_m1,
	test_osek_modes_modes_refined__the_proc_modes_modeDataClassifier_m2
} test_osek_modes_modes_refined__the_proc_modes_modeDataClassifier;
typedef enum e_test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_behaviorIdentifier_enum {
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_behaviorIdentifier_enum_input_data
} test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_behaviorIdentifier_enum;
typedef enum e_test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_m1_behaviorIdentifier_enum {
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_m1_behaviorIdentifier_enum_default_behavior,
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_m1_behaviorIdentifier_enum_input_data
} test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_m1_behaviorIdentifier_enum;
typedef enum e_test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_m2_behaviorIdentifier_enum {
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_m2_behaviorIdentifier_enum_default_behavior,
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_m2_behaviorIdentifier_enum_input_data
} test_osek_modes_modes_refined_refined_model__the_proc_modes_the_receiver_m2_behaviorIdentifier_enum;
typedef enum e_test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m1_currentState {
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m1_currentState_ModeSwitch_init_state,
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m1_currentState_ModeSwitch_final_state
} test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m1_currentState;
typedef enum e_test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m1_behaviorIdentifier_enum {
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m1_behaviorIdentifier_enum_default_behavior,
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m1_behaviorIdentifier_enum_p
} test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m1_behaviorIdentifier_enum;
typedef enum e_test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m2_currentState {
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m2_currentState_ModeSwitch_init_state,
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m2_currentState_ModeSwitch_final_state
} test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m2_currentState;
typedef enum e_test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m2_behaviorIdentifier_enum {
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m2_behaviorIdentifier_enum_default_behavior,
	test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m2_behaviorIdentifier_enum_p
} test_osek_modes_modes_refined_refined_model__the_proc_modes_the_proc_modes_mode_m2_behaviorIdentifier_enum;
typedef  int Base_Types__Integer;
typedef Base_Types__Integer test_osek_modes_modes_refined_refined_model__the_proc_modes_mode_m1_p_bufferType[2];
typedef port_queue_t OSEK_runtime__PortQueueType;
typedef Base_Types__Integer test_osek_modes_modes_refined_refined_model__the_proc_modes_mode_m2_p_bufferType[2];

#endif

