#ifndef __GENERATED_GTYPES_H__
#define __GENERATED_GTYPES_H__
#include "arinc653/types.h"
#include "arinc653/queueing.h"
typedef APEX_INTEGER arinc653_runtime__Queuing_Port_Id_Type;
typedef RETURN_CODE_TYPE arinc653_runtime__Return_Code_Type;
typedef  int common_pkg__Integer;
typedef MESSAGE_SIZE_TYPE arinc653_runtime__Message_Size_Type;
typedef SYSTEM_TIME_TYPE arinc653_runtime__System_Time_Type;
typedef enum e_test_queuing_refined_model__the_proc1_the_sender_behaviorIdentifier_enum {
	test_queuing_refined_model__the_proc1_the_sender_behaviorIdentifier_enum_default_behavior
} test_queuing_refined_model__the_proc1_the_sender_behaviorIdentifier_enum;
typedef enum e_test_queuing_refined_model__the_proc2_the_receiver_behaviorIdentifier_enum {
	test_queuing_refined_model__the_proc2_the_receiver_behaviorIdentifier_enum_default_behavior,
	test_queuing_refined_model__the_proc2_the_receiver_behaviorIdentifier_enum_p_in
} test_queuing_refined_model__the_proc2_the_receiver_behaviorIdentifier_enum;

#endif

