#ifndef __GENERATED_SUBPROGRAMS_H__
#define __GENERATED_SUBPROGRAMS_H__
#include "arinc653/time.h"
#include "arinc653/types.h"
#include "arinc653/queueing.h"
#include "user_code.h"
#include "gtypes.h"
#include "main.h"
void test_network_rtl8029_remote_communications_refined_model__the_proc2_the_receiver_entrypoint_impl(APEX_INTEGER *  p_in);

typedef enum {
  test_network_rtl8029_remote_communications_refined_model__the_proc2_the_receiver_entrypoint_impl_BA_entrypoint_init_state,
  test_network_rtl8029_remote_communications_refined_model__the_proc2_the_receiver_entrypoint_impl_BA_entrypoint_wait_dispatch_state,
  test_network_rtl8029_remote_communications_refined_model__the_proc2_the_receiver_entrypoint_impl_BA_entrypoint_exec_state,
  test_network_rtl8029_remote_communications_refined_model__the_proc2_the_receiver_entrypoint_impl_BA_entrypoint_final_state
} test_network_rtl8029_remote_communications_refined_model__the_proc2_the_receiver_entrypoint_impl_BA_State_t;


#endif

