/**
 * generated by Xtext
 */
package fr.tpt.aadl.ramses.transformation.trc.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class TRCOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
